### ISSUE TITLE
Setup auto config application for Prow 

### ISSUE THREAD

**Issue by bobcatfish** [tektoncd/plumbing#1]
# Expected Behavior
When we make changes to [our prow config](https://github.com/tektoncd/plumbing/blob/master/prow/config.yaml):

1. The pull request that proposes the changes should verify them as much as possible
2. Once they are merged, they should be automatically applied to our prow cluster

# Actual Behavior

1. We have nothing verifying our config.yaml changes
2. Once the changes are made, they must be applied manually with:

```bash
kubectl create configmap config --from-file=config.yaml=prow/config.yaml --dry-run -o yaml | kubectl replace configmap config -f -
```
# Additional Info

Bonus: can we do this via a Task/Pipeline? See https://github.com/tektoncd/pipeline/issues/267 for more info on our dogfood epic, will need [zenhub access](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md#project-stuff) to see subtasks.

**Comment by bobcatfish** [comment]
We might be able to use https://github.com/kubernetes/test-infra/tree/master/prow/plugins/updateconfig

**Comment by afrittoli** [comment]
Plan:
- define a service account `config-prow`
- define a secret in the `dogfooding` cluster that holds `config-prow`'s token
- define an event-listener / template / binding in the `dogfooding` cluster that uses `config-prow` credentials to update the config in the `prow` cluster

We can then use a k8s CronJob to trigger the event listener, and run the job e.g. hourly.
Once we have the event listener in place we might even hook it to a merge events in the plumbing repo.

**Comment by afrittoli** [comment]
Something along this lines: https://github.com/tektoncd/plumbing/pull/98
