### ISSUE TITLE
Add ghproxy for prow components

### ISSUE THREAD

**Issue by sbwsg** [tektoncd/plumbing#1010]
### Feature request

Add the configuration required to run [ghproxy](https://github.com/kubernetes/test-infra/tree/master/ghproxy) so that prow components running in our clusters do not hit rate limits.

### Use case

Most recently we experienced a 20 minute pause during a peribolos sync running in our dogfooding cluster. The log from that run [is available here](https://gist.github.com/sbwsg/3ba1882943281fe44b14d767efffe80d).

At the start of the log the following message is printed:

> It doesn't look like you are using ghproxy to cache API calls to GitHub! This has become a required component of Prow and other components will soon be allowed to add features that may rapidly consume API ratelimit without caching. Starting May 1, 2020 use Prow components without ghproxy at your own risk! https://github.com/kubernetes/test-infra/tree/master/ghproxy#ghproxy

About halfway through the following message appears:

```json
"Throttled clientside for more than 15 minutes","throttle-duration":"19m50.614173394s","throttled":true
```

**Comment by afrittoli** [comment]
ghproxy is now deployed and configured for prow.
Tekton components still not benefit from it though - but that's a different issue.
