### ISSUE TITLE
Tektoncd project convention for pipeline-as-code

### ISSUE THREAD

**Issue by vdemeester** [tektoncd/plumbing#102]
This has been discussed a tiny bit during [last working group](https://docs.google.com/document/d/1rPR7m1Oj0ip3bpd_bcS1sjZyPgGi_g9asF5YrExeESc/edit#heading=h.4mbsfb4pxpoh).

As of today, each project that uses Tekton to do some work (release most likely), is using a `tekton` folder. Now that we are getting more into *dogfooding* and that we are able to start experimenting with *pipeline-as-code* (thanks to [`tektoncd/triggers`](https://github.com/tektoncd/triggers) and #100, we should **try to define a convention** for the `tektoncd` projects (nothing official yet).

Few questions we may want to answer
- One file vs a folder with multiple files possible ?
- Hidden folder or not (aka `tekton/` vs `.tekton/`) ?
- Experimenting with a DSL (from experimental maybe) or stick with plain yaml ?

All those questions do not need to be answer at the same time, and the answer might evolve over time. This issue is there to track the work around that.

/cc @bobcatfish @dibyom @skaegi @chmouel @mnuttall @ImJasonH @vtereso @afrittoli @dlorenc @sbwsg @akihikokuroda @abayer

**Comment by vtereso** [comment]
@bobcatfish Good points. With consideration for a DSL, this could be one determining factor to decide between one file vs a folder, but otherwise could probably be pushed out.

Other questions about the convention: Is it correct to assume convention means nothing is _internal_ hard coded, but rather tooling/platforms like JenkinsX will build on this standard? Like Christie mentioned, is this convention anything other than pathing for the sake of discoverability?

**Comment by vdemeester** [comment]
> In the tools discoverability category I can see some sub points (maybe these are out of scope for what you have planned here tho @vdemeester ):
> 
>     * Avoiding duplication between tektoncd projects
>     * Applying some kind of standards across tektoncd projects (e.g. all projects should have x % coverage, coverage should only increase, a code of conduct must always be present)
>     * ?
+:100:

> > Experimenting with a DSL (from experimental maybe) or stick with plain yaml ?
> 
> I feel like this is a discussion we could make better decisions around if we delay it until after we've established conventions around the existing syntax.

@bobcatfish agreed !

> Other questions about the convention: Is it correct to assume convention means nothing is internal hard coded, but rather tooling/platforms like JenkinsX will build on this standard?

@vtereso depends on what you mean by *internal* hard coded, but yeah, there shouldn't be anything in the core projects (pipeline, triggers, …) that are hard coded for our use. And yeah, the "hope" is that tooling/platforms build on those standards, although it's not a goal per-se (everybody is free :angel: and JenkinsX is already existing and kinda mature, so in this case, I'm not sure it would go towards following those standards if they are far from their approach).

> Like Christie mentioned, is this convention anything other than pathing for the sake of discoverability?

Yeah, in the scope of the `tektoncd` project at first. I don't want to set a huge goal for this ; at first I just want to make `tektoncd` projects using `tektoncd` projects to build and all follow the same convention, for the sake of discoverability and less duplication.
