### ISSUE TITLE
Consider enabling dependabot across Tekton repos

### ISSUE THREAD

**Issue by imjasonh** [tektoncd/plumbing#1028]
https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuring-dependabot-version-updates

Dependabot sends a PR for each updated dependency (one PR per updated dependency), on a configurable schedule (daily, weekly, etc.).

Keeping dependencies up to date means getting security/performance fixes faster, while keeping pinned deps for build stability.

Based on experience using Dependabot in other projects, I'd suggest the following:
- Before enabling Dependabot on a repo, do one big manual dep update (`go get -u ./...`). This avoids a flood of PRs if there are many outdated deps.
- Configure weekly updates. Daily updates can get toilsome and doesn't provide a lot of benefit.
- If the automated Dependabot flow doesn't work for us (it doesn't `update-codegen.sh`, and we might need that), consider writing a script to bump deps ourselves (e.g., `go get -u ./... && ./update-codegen.sh`) and using GitHub Actions to run it on a schedule and create PRs ([example](https://github.com/google/go-containerregistry/blob/main/.github/workflows/bump-deps.yaml))
- Try it out on smaller/simpler repos first -- CLI or Triggers, before Pipeline.

If this becomes toilsome or time-consuming, we can disable it and try to come up with some other workflow to keep deps up to date.

**Comment by imjasonh** [comment]
Sounds like we're in general agreement that this is worth moving forward on. (If you disagree, please speak soon!)

@vdemeester would like to start with the CLI repo, and I think that sounds fine. I'd like to give it a week or two (a couple weekly dependabot cycles) before proceeding, to make sure we like the workflow.

Before we send a PR to enable Dependabot, we should make sure deps are up to date.

**Comment by AlanGreene** [comment]
Dependabot seems to be enabled for the dashboard repo. I'm not sure when/how this was enabled but I've definitely seen a few dependabot PRs come in. So far there hasn't been a flood, and usually the PRs come just as we're looking at updating dependencies anyway. Consider this my vote for making it official 👍

**Comment by vdemeester** [comment]
Hub is on as well : https://github.com/tektoncd/hub/pull/407

**Comment by vdemeester** [comment]
- [x] `tektoncd/hub` https://github.com/tektoncd/hub/pull/407
- [ ] `tektoncd/pipeline` https://github.com/tektoncd/pipeline/pull/4915
- [ ] `tektoncd/chains` https://github.com/tektoncd/chains/tree/main/.github/dependabot.yml
- [ ] `tektoncd/cli` https://github.com/tektoncd/cli/pull/1579
- [ ] `tektoncd/operator` https://github.com/tektoncd/operator/pull/826
- [ ] `tektoncd/triggers`
- [ ] `tektoncd/results` https://github.com/tektoncd/results/pull/168
- [ ] `tektoncd/catlin`

**Comment by vdemeester** [comment]
/lifecycle frozen 
Still two repository to enable 👼🏼

**Comment by vdemeester** [comment]
I think overall, we can consider this done 👼🏼 New repositories can enable this on demand.
