### ISSUE TITLE
Metrics for integration test failures and latencies

### ISSUE THREAD

**Issue by lbernick** [tektoncd/plumbing#1044]
We should develop continuous metrics for integration test passes and failures, and their latencies. This will help us identify when test failures could be due to flakes, and figure out which tests are providing signal and which are just providing noise. It will also help us determine if efforts to improve integration test latency work. These metrics should be on the level of individual test classes, not just test suites.

One option here is [TestGrid](https://github.com/GoogleCloudPlatform/testgrid), although it's in the process of being open sourced.

**Comment by lbernick** [comment]
/remove-lifecycle rotten

We do have a testgrid setup at https://testgrid.k8s.io/tektoncd-pipeline, but it doesn't display anything useful. I made another attempt today to actually try to get it to display something useful; however, testgrid is really poorly documented and I'm struggling to figure out how.

My larger concern is that there's no way to run the frontend locally without using google-internal tools, and testgrid doesn't show signs of open-sourcing their frontend any time soon. I'm concerned that only Google employees (and likely only me) will be able to test out changes to our testgrid config even if I do get this working.

Starting to think TestGrid is not the way to go here. A better option could be using Tekton to automate some of the scripts I have [here](https://github.com/lbernick/tekton-test-scripts). (These scripts are pretty hacky-- they just parse Github comments for the number of times people reran tests.) We could also just have all of our Prow jobs kick off Tekton Pipelines and use the dashboard, but the disadvantage is that this strategy will take some time and a lot of effort.

@dibyom wdyt?

**Comment by dibyom** [comment]
> A better option could be using Tekton to automate some of the scripts I have [here](https://github.com/lbernick/tekton-test-scripts). (These scripts are pretty hacky-- they just parse Github comments for the number of times people reran tests.)

+1. We can just upload the results to a bucket or something and then either manually ingest them into a spreadsheet or some kind of data analysis tool like big query

> We could also just have all of our Prow jobs kick off Tekton Pipelines and use the dashboard, but the disadvantage is that this strategy will take some time and a lot of effort.

I think Prow support for Tekton is for a very old version of Pipelines

**Comment by lbernick** [comment]
One problem with my scripts is that they count the number of times a dev commented `/retest` and assumes that this is caused due to a test flake. This is increasingly not the case. Maybe we ask people to stop rerunning CI as much as possible?

**Comment by dibyom** [comment]
>  Maybe we ask people to stop rerunning CI as much as possible?

We could but I wonder how well that'd work 😝 

>  This is increasingly not the case.

Why else would folks want to rerun tests unless it is to pass a failing test?

**Comment by lbernick** [comment]
I think people are re-running failed tests that are not flakes unfortunately-- not sure why
