### ISSUE TITLE
Scale Prow Cluster

### ISSUE THREAD

**Issue by xchapter7x** [tektoncd/plumbing#1059]
# [writeup](https://docs.google.com/document/d/15Gza5Rj5MIzD0Ye2r_lbURreDhyeFOufvdC3E9lllbo/edit?usp=sharing&resourcekey=0-Lpi8BbXXtl4S7IJgi-V67g)

We're scaling the CPU in our prow cluster in order to (hopefully) address what we think are infrastructure flakes, causing test failure/flakes

**Comment by xchapter7x** [comment]
were now running fully on `highcpu` instances
https://pantheon.corp.google.com/kubernetes/clusters/details/us-central1-a/prow/nodes?project=tekton-releases

will touch back with some metrics and outcomes before closing this issue.

**Comment by dibyom** [comment]
We tried scaling up to e2-standard-32 VMs as well

**Comment by xchapter7x** [comment]
@dibyom I haven't tracked the results of the latest changes. 
are our flakes reduced at all? I just want to log an outcome here before I close the issue.

**Comment by dibyom** [comment]
hey @xchapter7x our flakes did reduce but it ended up being a combination of things - scaling up did not initially help with flakes but exposed resource contention issues i.e. our prow jobs did not set resource limits and requests. Adding resource requests/limits to our jobs + fine tuning our node pools (both sizing + type of machines: n2 vs e2 for some jobs) helped reduce infra related flakes (we still have some tests that themselves are flaky). 
/cc @abayer and @afrittoli
