### ISSUE TITLE
Automate plumbing infra using Terraform

### ISSUE THREAD

**Issue by dibyom** [tektoncd/plumbing#1137]
### Feature request

We should use Terraform to automate our CI infra. We've been quite a few changes to it recently and having it in this repo would make it more visible.

We can use something like https://github.com/GoogleCloudPlatform/terraformer to get the initial state into git

### Use case

- Tracking/reviewing updates to CI infra in as code
- Make it easy to recreate our infra/move it across projects

**Comment by abayer** [comment]
@afrittoli and I just talked about this a bit in the productivity WG. It sounds like we're going to be getting the new billing org etc set up soon, and I feel like that creates a good opportunity for us to put together a Terraform setup to be used in creating/maintaining the new cluster(s).
