### ISSUE TITLE
Try out GH auto merge and merge queue

### ISSUE THREAD

**Issue by dibyom** [tektoncd/plumbing#1138]
### Feature request

Currently, we use Tide to manage merging PRs when tests pass. GitHub has also now similar functionality:

1. https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-auto-merge-for-pull-requests-in-your-repository

2. https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/merging-a-pull-request-with-a-merge-queue

### Use case
- This could simplify some of our CI configuration but also help us move towards https://github.com/tektoncd/plumbing/issues/912

### Approach

- [ ] 1. Try experimenting with auto merge with a lower traffic repo (where we probably don't need the merge queue) e.g. triggers/cli/operator
- [ ] 2. Wait till we are in  merge queue beta
- [ ] 3. Modify our CI jobs to run on pushes to `gh-readonly-queue/` branch: https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue#about-merge-queues
- [ ] 4. Try merge queue in one of the lower traffic repos
- [ ] 5. If experiment is successful, try with tektoncd/pipeline

**Comment by afrittoli** [comment]
Thanks Dibyo - I think it would be ok to experiment.
I'm a bit wary about switching an open source tool like tide for a closed source alternative though.

**Comment by dibyom** [comment]
> I'm a bit wary about switching an open source tool like tide for a closed source alternative though.

That's a fair concern but we do already use GItHub for a lot already :) My main motivation though was that I wasn't sure if we could still rely on tide when we are fully off of Prow for running our presubmit tests (maybe we can and I'm wrong)
