### ISSUE TITLE
Restore access to wlynch for tekton-release resources

### ISSUE THREAD

**Issue by wlynch** [tektoncd/plumbing#1150]
My tekton-releases access was tied to my previous job's email, and I never regained access. I need the permissions again to handle a Chains release. Can someone with access run this command?

```
python adjustpermissions.py --users "billy@chainguard.dev"
```

Also could I get readded to tekton-vmt as well? 🙏 

Thanks!

**Comment by afrittoli** [comment]
For the cluster permissions, I tried, but at least until we have new GCP org/project, I'm not allows, it would have to be someone at Google, @dibyom may be able to help.

I re-invited you to the tekton-vmt group, thank you for your service there!

**Comment by dibyom** [comment]
Done. @wlynch let me know if you don't have access now
