### ISSUE TITLE
check-pr-has-kind-label is not run when a label is added

### ISSUE THREAD

**Issue by dibyom** [tektoncd/plumbing#1165]
# Expected Behavior

When I comment `/kind feature` I expect the check-pr-has-kind-label to run

# Actual Behavior

Adding a label with a comment does not seem to trigger this check. I have to manually run the test using `test check-pr-has-kind-label` for it to run

# Additional Info

https://github.com/tektoncd/pipeline/pull/5170#issuecomment-1194546771 as an example

**Comment by abayer** [comment]
Fixed by #1169
