### ISSUE TITLE
Support for Extenal-secret-operator on upstream dogfooding cluster

### ISSUE THREAD

**Issue by Basavaraju-G** [tektoncd/plumbing#1187]
### Feature request
Support for external secret operator on dogfooding cluster. https://dashboard.dogfooding.tekton.dev

### Use case
As of now secrets created for others arch like 'ppc64le/s390x' are done manually. To have more control over secrets created by users, would like to have support for external secret operator installed on dogfooding cluster.  once the operator installed, we will be able to use Google/IBM Cloud Secret Manager to manage secrets.

Refernces:
https://external-secrets.io/v0.5.9/

**Comment by dibyom** [comment]
An alternative would be to use the secret store CSI driver with the newly introduced csi workspaces feature
