### ISSUE TITLE
Migrate go coverage task to Tekton

### ISSUE THREAD

**Issue by chitrangpatel** [tektoncd/plumbing#1239]
`go coverage task` is run by prow. In the interest of dogfooding, we should migrate this to run as a `Tekton pipeline`. The outcome should be the same regardless of whether we run the job on the prow cluster on using Tekton ie.
- We need a PR comment with the coverage report on GitHub.
- We need to upload the artifacts to the tekton-prow bucket so that it can be picked up by Prow's Spyglass.
- We need to update the status of the task on Github in case of success or failure.

To that effect, here is a draft plan that will keep evolving as I learn the details more:

- [x] Write a go coverage Tekton task to run the coverage in Tekton.
- [x] Ensure that the coverage report is sent to the PR on GitHub.
- [x] Upload the artifacts and logs to the tekton-prow GCS bucket.
- [ ] Deploy on the pipelines repository.
- [ ] Compare coverage reports with ones generate by the job running on the prow cluster.
- [ ] Stop using the prow jobs and transition over completely.

**Comment by afrittoli** [comment]
https://github.com/tektoncd/plumbing/pull/1249

**Comment by chitrangpatel** [comment]
This can now be closed. The jobs on the dogfooding cluster seem to be running fine and when clicking on details, it takes users to the tekton dashboard with the logs etc.
