### ISSUE TITLE
Implement tekton-pipeline-beta-integration-test in prow CI

### ISSUE THREAD

**Issue by chitrangpatel** [tektoncd/plumbing#1242]
### Feature request

Now that we have an additional `enable-api-fields` value of `beta`, we need to enable integration tests that enable this feature flag before running the e2e tests on the prow cluster.
 
### Use case

When the prow cluster runs the `alpha-integration` tests, it added environment variables as show [here](https://github.com/tektoncd/plumbing/blob/541dbe23d81ab60bab99c9b47fc41e927dbae513/prow/config.yaml#L1297-L1356) to enable `api-fields` and `embedded-status`. If some code logic requires that `enable-api-fields` is set to `beta`, that piece of logic will not be tested in the integration tests because the cluster will currently, either set the value of the feature flag to `alpha` or `stable`. Thus, beta features will not be tested in integration tests. 

Enabling this test will allow us to conduct integration tests for `beta` features.

**Comment by chitrangpatel** [comment]
cc @dibyom @afrittoli @abayer @vdemeester (since you probably know much more about this 🙂  )

**Comment by dibyom** [comment]
We'd need something like this at least: https://github.com/tektoncd/pipeline/blob/main/test/e2e-tests-kind-prow-alpha.env
