### ISSUE TITLE
Install golangci-lint from a release instead of master

### ISSUE THREAD

**Issue by vdemeester** [tektoncd/plumbing#125]
When building the test-runner image, we are installing `golangci-lint` from master (using `RUN go get -u github.com/golangci/golangci-lint/cmd/golangci-lint`).

We should install it from a release version instead to make sure its behavior doesn't change implicitly when bumping the test-runner image.

/cc @chmouel 

Ref: tektoncd/pipeline#1634

/area test-infra

**Comment by chmouel** [comment]
FYI the authors does not  advise to use the `go get` version https://github.com/golangci/golangci-lint#go-get  (but we can maybe get away with that)

I think we need a stable tag and not just a specific version that we need to (forget) update manually everytime,

**Comment by wlynch** [comment]
triggers needs Go 1.13, so we'll need to pin golangci-lint to >= v1.19.0
