### ISSUE TITLE
Migrate to CDF GCP projects

### ISSUE THREAD

**Issue by chitrangpatel** [tektoncd/plumbing#1257]

**Comment by dibyom** [comment]
Duplicate of https://github.com/tektoncd/plumbing/issues/865

**Comment by chitrangpatel** [comment]
Thanks @dibyom I can close this and instead add #865 to the project board since it has all the context.

**Comment by chitrangpatel** [comment]
> Thanks @dibyom I can close this and instead add #865 to the project board since it has all the context.

You're well ahead of me 😄
