### ISSUE TITLE
Convention for storing non-pipeline yamls for CI

### ISSUE THREAD

**Issue by chitrangpatel** [tektoncd/plumbing#1261]
Convention for storing Trigger and other non pipeline YAMLs for CI. This has to wait until we can use workflows and then determine the conventions.

**Comment by dibyom** [comment]
I think this was meant for deploying workflow yamls ....but that has to wait until we can use workflows :)

**Comment by chitrangpatel** [comment]
Needs context (ping @dibyom )

**Comment by dibyom** [comment]
see https://github.com/tektoncd/plumbing/issues/1261#issuecomment-1310686455
