### ISSUE TITLE
Extend CD mechanism to deploy non-pipeline yamls 

### ISSUE THREAD

**Issue by chitrangpatel** [tektoncd/plumbing#1262]
Extend the current plumbing cd mechanism to deploy the [YAMLs](#1261 )

**Comment by afrittoli** [comment]
I'm not sure what this refers to.
The existing CD mechanism deploys all kind of YAMLs - it's based on `kustomize` and `kubectl`.

**Comment by dibyom** [comment]
I think this was meant for deploying workflow yamls ....but that has to wait until we can use workflows :)

**Comment by chitrangpatel** [comment]
Needs context (ping @dibyom )
