### ISSUE TITLE
Build one pipeline with all CI tasks

### ISSUE THREAD

**Issue by chitrangpatel** [tektoncd/plumbing#1266]

**Comment by abayer** [comment]
I'm honestly not sure if this is a desirable goal - we want to be able to re-run individual jobs, which would be a hassle with a single `Pipeline`.

**Comment by chitrangpatel** [comment]
Is this something we want to get towards? Or something we should just drop?

**Comment by chitrangpatel** [comment]
It seems that its going to be challenging (or something that we dont want to enable) for now. I'm closing this. We can reopen it later if we feel otherwise.
