### ISSUE TITLE
Automate secure webhook creation flow for setting up a new trigger

### ISSUE THREAD

**Issue by chitrangpatel** [tektoncd/plumbing#1267]
Currently, creating a webhook on GitHub and connecting it to an EventListener is a manual operation. 
We could automate this by using a Task, another events based project (like knative events), Pipelines as Code, or Workflows. 
- copied from https://github.com/tektoncd/plumbing/issues/1267#issuecomment-1447027063

**Comment by dibyom** [comment]
I think Workflows is tacking this and we can adopt workflows for dogfooding to solve this

**Comment by chitrangpatel** [comment]
Needs context (ping @dibyom )

**Comment by dibyom** [comment]
Currently, creating a webhook on GitHub and connecting it to an EventListener is a manual operation. We could automate this by using a Task, another events based project (like knative events), Pipelines as Code, or Workflows.
