### ISSUE TITLE
Simplified convention for storing Trigger resources

### ISSUE THREAD

**Issue by chitrangpatel** [tektoncd/plumbing#1268]
Currently, we need to update TriggerTemplate if Pipeline changes. There are also other conventions around passing around standard params etc. that are specific to the plumbing CI. We should find a way to simplify this e.g. using a project like pipelines as code or workflows

**Comment by dibyom** [comment]
Workflows should solve this

**Comment by chitrangpatel** [comment]
Needs context (ping @dibyom )
