### ISSUE TITLE
GH status notifications

### ISSUE THREAD

**Issue by chitrangpatel** [tektoncd/plumbing#1270]
- [ ] Explore something like https://github.com/cloudposse/github-status-updater
- [ ] Or use Billy's controller for status updates
- [ ] Or use a finally task
- [ ] [Andrew wrote a pr-commenter custom task](https://github.com/tektoncd/plumbing/pull/1205)

**Comment by abayer** [comment]
This is done via https://github.com/tektoncd/plumbing/tree/main/tekton/ci/custom-tasks/pr-status-updater
