### ISSUE TITLE
Replace Gubernator with Tekton Persistent Logs(TEP-0117)

### ISSUE THREAD

**Issue by chitrangpatel** [tektoncd/plumbing#1274]

**Comment by afrittoli** [comment]
After the upgrade to Prow we now use Spyglass and not Gubernator anymore. 
We still have jobs called gubernator-* and what they do is upload log files in a GCP bucket for spyglass to consume.
It would be great of course to have logs through Tekton Results - but that only works as long as we can provide an integration with Spyglass or a replacement for it.
