### ISSUE TITLE
 Proposal for PR testing on Multiple architectures 

### ISSUE THREAD

**Issue by Basavaraju-G** [tektoncd/plumbing#1277]
### Feature request
Today, Tekton supports multiple architectures like amd64, ppc64le, s390x.  We are already running e2e tests for P/Z on dogfooding cluster. https://dashboard.dogfooding.tekton.dev/#/namespaces/bastion-z/ 
as of now we are running only on nightly-releases,  it would be good if we ran e2e on every PR with flags like /test-s390x, /test-ppc64le.

**Comment by afrittoli** [comment]
Thanks @Basavaraju-G, this looks great.
One question on this:

> it would be good if we ran e2e on every PR with flags like /test-s390x, /test-ppc64le.

flags like `/test-s390x`, `/test-ppc64le` would be used to trigger those tests on demand. Is the proposal to run those tests against *all* PRs or exclusively on demand?

**Comment by Basavaraju-G** [comment]
@afrittoli  we would like to test against all PRs if possible.

**Comment by afrittoli** [comment]
Pipeline CI Job definition in prow config: https://github.com/tektoncd/plumbing/blob/fa0f5c274777261077164e4cc612195d883b480a/prow/config.yaml#L1242-L1296

For the nodepool, we use machine type "n2-standard-4"  (see https://cloud.google.com/compute/docs/general-purpose-machines) - the pool is configured for autoscaling up to 24 nodes.

<img width="616" alt="image" src="https://user-images.githubusercontent.com/2205608/202167217-97f90ae1-1d49-4dce-ae01-65443334604f.png">
<img width="609" alt="image" src="https://user-images.githubusercontent.com/2205608/202167418-efe643b2-338a-4ccc-b2e6-f8725faf9120.png">

@abayer Anything important that I missed?
