### ISSUE TITLE
Keep required Kubernetes version synced in prow/config.yaml

### ISSUE THREAD

**Issue by JeromeJu** [tektoncd/plumbing#1283]
### Feature request

The required Kubernetes version in prow/config for example https://github.com/tektoncd/plumbing/blob/main/prow/config.yaml#L838 is hardcoded and this should be synced or have a way to be updated once Tektoncd have updated the required version.

### Use case

https://github.com/tektoncd/plumbing/pull/1279#discussion_r1025475830

**Comment by vdemeester** [comment]
> ### Feature request
> The required Kubernetes version in prow/config for example https://github.com/tektoncd/plumbing/blob/main/prow/config.yaml#L838 is hardcoded and this should be synced or have a way to be updated once Tektoncd have updated the required version.
> 
> ### Use case
> [#1279 (comment)](https://github.com/tektoncd/plumbing/pull/1279#discussion_r1025475830)

I think, ideally, prow itself shouldn't have that information, and everything would "come" from each component.

**Comment by JeromeJu** [comment]
Thanks @vdemeester , that makes perfect sense. So that being said, we might need to put this into a checklist whenever we are updating the required version?

**Comment by vdemeester** [comment]
@JeromeJu yes, and this is also ideally, and we might still need to handle this in plumbing for some time, so yes we definitely need some up-to-date checklist here and on each component repositories on what to do when we update the min k8s version we support.
