### ISSUE TITLE
Taskloop not running on dogfooding

### ISSUE THREAD

**Issue by afrittoli** [tektoncd/plumbing#1300]
# Expected Behavior

Taskloop is running 

# Actual Behavior

```
deployment.apps/tekton-taskloop-controller          0/1     0            0           661d
deployment.apps/tekton-taskloop-webhook             0/1     0            0           661d
```

# Additional Info

Taskloop is not maintained anymore now that we have matrix. 
We should either produce a new release of taskloop that supports the current version of k8s, or remove taskloop and adopt matrix in dogfooding. I think the only blocker there was the availability of array results but since that's implemented now, we should be able to switch.

**Comment by AlanGreene** [comment]
has an 'important' label so shouldn't rot
/remove-lifecycle rotten

**Comment by afrittoli** [comment]
With `matrix`, taskloop is deprecated and will not be used in dogfooding nor supported in anymore.
