### ISSUE TITLE
Remove deprecated API usages from dogfooding for K8s 1.23

### ISSUE THREAD

**Issue by dibyom** [tektoncd/plumbing#1326]
GCP recommendations: https://console.cloud.google.com/home/recommendations/view-link/projects/574248271492/locations/us-central1-a/recommenders/google.container.DiagnosisRecommender/recommendations/737720a4-32bf-4e84-96e2-766b204fc9ee;source=webSubtask?project=tekton-releases

**Comment by lbernick** [comment]
@dibyom it looks like dogfooding and prow are both on k8s 1.24 now, can this be closed?

**Comment by dibyom** [comment]
For dogfooding, I see the following:


In the last 30 days, API clients in your cluster attempted to call APIs that were removed in Kubernetes 1.22. These APIs are no longer available. Functionality that depends on these APIs might be broken. [Learn more](https://cloud.google.com/kubernetes-engine/docs/deprecations/apis-1-22)



API | User agent | Total calls (last 30 days) | Last called |  
-- | -- | -- | -- | --
/apis/certificates.k8s.io/v1beta1/certificatesigningrequests | kube-state-metrics/v1.9.7 (linux/amd64) kube-state-metrics/b3fa5852 | 2576853 | June 21, 2023 at 5:34:00 PM UTC-4 |  
/apis/extensions/v1beta1/ingresses | kube-state-metrics/v1.9.7 (linux/amd64) kube-state-metrics/b3fa5852 | 2576804 | June 21, 2023 at 5:41:00 PM UTC-4 |  
/apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings | okhttp/3.12.6 | 18506 | June 21, 2023 at 5:47:00 PM UTC-4 |  


For Prow:



API | User agent | Total calls (last 30 days) | Last called |  
-- | -- | -- | -- | --
/apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions | webhook/v0.0.0 (linux/amd64) kubernetes/$Format | 2565890 | June 21, 2023 at 5:48:00 PM UTC-4 |  
/apis/admissionregistration.k8s.io/v1beta1/validatingwebhookconfigurations | webhook/v0.0.0 (linux/amd64) kubernetes/$Format | 2565869 | June 21, 2023 at 5:35:00 PM UTC-4 |  
/apis/admissionregistration.k8s.io/v1beta1/mutatingwebhookconfigurations | webhook/v0.0.0 (linux/amd64) kubernetes/$Format | 2565869 | June 21, 2023 at 5:34:00 PM UTC-4 |  
/apis/extensions/v1beta1/ingresses | controller/v0.0.0 (linux/amd64) kubernetes/$Format/jetstack-cert-manager/v0.12.0 | 2534000 | June 21, 2023 at 5:35:00 PM UTC-4
