### ISSUE TITLE
Udated prow to the latest version

### ISSUE THREAD

**Issue by afrittoli** [tektoncd/plumbing#138]
# Motivation
The latest version of Prow supports a more recent version of Tekton, so we should update both Prow and Tekton in the `prow` cluster and benefit from that. 
It would be nice to get rid of pipelines with `${}` and other legacy syntax for good.

# Task details
Since `prow` runs our CI system, we need to make sure the update is as swift as possible. It would be nice to have a rollback plan in place should things go wrong.
We should write down a detailed update and rollback process. 
Prow + Tekton is only used for nightly builds, and those are also built by Tekton alone in the dogfooding cluster, so we can do the two updates pretty much in isolation one from the other.

**Comment by bobcatfish** [comment]
It's a pretty rough read but I tried to write down what I did last time at https://github.com/tektoncd/plumbing/blob/master/prow/README.md#updating-prow-itself
