### ISSUE TITLE
Upgrade kind-based integration tests to a newer k8s version

### ISSUE THREAD

**Issue by lbernick** [tektoncd/plumbing#1499]
Integration tests with kind currently use k8s 1.24, which [will reach its EOL this month](https://kubernetes.io/releases/#release-v1-24). We'll need to upgrade our [test-runner image](https://github.com/tektoncd/plumbing/blob/main/tekton/images/test-runner/setup-kind.sh) to support newer k8s versions (which will likely also require a newer kind version), and then update our [prow config](https://github.com/tektoncd/plumbing/blob/main/prow/config.yaml) to use the new image and new k8s versions.

**Comment by vdemeester** [comment]
Yes, we are now running 1.25.
