### ISSUE TITLE
Prow cert is expired?

### ISSUE THREAD

**Issue by bobcatfish** [tektoncd/plumbing#150]
# Expected Behavior

https should work for prow.tekton.dev

# Actual Behavior

As pointed out by @chmouel when you visit prow.tekton.dev (e.g. https://prow.tekton.dev/log?job=pull-tekton-pipeline-unit-tests&id=1204443482555420674 to look at the raw build log for https://github.com/tektoncd/pipeline/pull/1702) you see an error like this:

![image](https://user-images.githubusercontent.com/432502/70567576-32222700-1b64-11ea-8e54-5b693a3a4f59.png)

# Additional Info

Everything we know about how the certs work is written at https://github.com/tektoncd/plumbing/tree/master/prow#ingress - also @dlorenc will know more if he wants to jump in here :D

p.s. as a follow up to fixing this immediate issue we should open an issue to proactively prevent this in the future (unless we feel its not worth the effort)

**Comment by vdemeester** [comment]
/kind bug

This is fixed now, see #152
/close
