### ISSUE TITLE
Markdown Link check is failing for valid URLs

### ISSUE THREAD

**Issue by dibyom** [tektoncd/plumbing#157]
# Expected Behavior
Markdown link check is should pass!

# Actual Behavior
Markdown link check is failing for valid URLs e.g. https://github.com/tektoncd/triggers/pull/273
I can reproduce this locally from the Triggers repo.

# Steps to Reproduce the Problem

`liche -d $(pwd) -v $(find docs/ -name *.md)`

# Additional Info
Failing URLs:

## https://github.com/tektoncd/triggers/pull/275
```
I1212 16:03:05.422] 	ERROR	https://docs.gitlab.com/ee/user/project/integrations/webhooks.html#events
I1212 16:03:05.422] 		Not Found (HTTP error 404)
I1212 16:03:05.422] 	ERROR	https://docs.gitlab.com/ee/user/project/integrations/webhooks.html/
I1212 16:03:05.422] 		Not Found (HTTP error 404)
```

## https://github.com/tektoncd/pipeline/pull/1736
```
I1212 08:38:19.837] docs/tasks.md
I1212 08:38:19.837] 	ERROR	https://en.wikipedia.org/wiki/Shebang_(Unix
I1212 08:38:19.838] 		Not Found (HTTP error 404)
```

## https://github.com/tektoncd/pipeline/pull/1696

```
I1211 16:59:30.399] ---- Checking links in the markdown files ----
I1211 16:59:30.399] ----------------------------------------------
I1211 16:59:32.799] docs/resources.md
I1211 16:59:32.800] 	ERROR	https://godoc.org/github.com/jenkins-x/go-scm/scm#State
I1211 16:59:32.800] 		Not Found (HTTP error 404)

```

**Comment by bobcatfish** [comment]
Is it possible the URLs are sometimes down? Maybe we can make a list of the URLs we are seeing fail. 

Ideas:
* could make the markdown lint checker more tolerant (e.g. retry)
* make the markdown lint check not required

**Comment by dibyom** [comment]
Maybe related: https://github.com/raviqqe/liche/pull/24

**Comment by dibyom** [comment]
Problem might be in fasthttp v.1.5

https://gist.github.com/dibyom/e546f71828d2d0886fc9c14b639f535d

**Comment by vdemeester** [comment]
Honestly, I would like to limit the check to internal files as it's way more useful than old files :angel:

**Comment by dibyom** [comment]
Yeah, I don't think checking links only for changed markdown files on PRs is super useful -- if a markdown file is not touched for months, and in that time any of the links go stale, we would not catch it unless someone modifies the file. 
Running this tool locally though, I did discover quite a few URLs that currently 404 or end with a `.` making them invalid.
