### ISSUE TITLE
Create a `Task` that can create a Tekton Pipelines cluster to test against

### ISSUE THREAD

**Issue by bobcatfish** [tektoncd/plumbing#171]
## Expected Behavior
We should be testing and releasing Pipelines with Pipelines.

We should have a `Task` (and related Resources) defined that we can use to:
- Create a cluster to test against (currently done using boskos and triggered by [e2e-tests.sh](https://github.com/knative/build-pipeline/blob/master/test/e2e-tests.sh))
- Deploy Pipelines to the cluster

### The Task

* Inputs:
  - git repo
  - cluster (to deploy Pipelines to and run end to end tests) (or is this an output?)
* Outputs:
  - cluster

## Actual Behavior

We currently use [prow](https://github.com/knative/test-infra/tree/master/ci/prow) and [e2e-tests.sh](https://github.com/knative/build-pipeline/blob/master/test/e2e-tests.sh), which also uses [boskos](https://github.com/kubernetes/test-infra/tree/master/boskos) to control clusters to test against.

## Additional Info

* If possible let's try to keep using [the boskos cluster we were already using](https://github.com/knative/test-infra/tree/master/ci/prow/boskos)
* Actually triggering this is not in scope for this issue, it's fine to test manually (we'll be linking these together in a later issue)

**Comment by afrittoli** [comment]
I wonder if we could do this in go (instead of Task) and wrap it in an interceptor, so that the body of the trigger request is enriched with the data to setup the cluster resource in the trigger template. Just an idea

**Comment by bobcatfish** [comment]
We do have some of this work in progress for our catalog testing:

* [boskos-acquire](https://github.com/tektoncd/catalog/tree/master/task/boskos-acquire)
* [boskos-release](https://github.com/tektoncd/catalog/tree/master/task/boskos-release)
* [gke-cluster-create](https://github.com/tektoncd/catalog/tree/master/task/gke-cluster-create)

More details in https://github.com/tektoncd/catalog/issues/373
