### ISSUE TITLE
Build log is missing in the pipeline nightly release bucket

### ISSUE THREAD

**Issue by afrittoli** [tektoncd/plumbing#181]
# Expected Behavior
The pipeline log should be stored along to the release.yaml in the bucket

# Actual Behavior
It is not (anymore) https://console.cloud.google.com/storage/browser/tekton-releases-nightly/pipeline/latest?project=tekton-nightly

**Comment by afrittoli** [comment]
After the upgrade to trigger v0.2.0, JSONPath replaced gjson in trigger bindings. 
The new jsonpath expression seems to cause issues:
```
{"level":"error","logger":"eventlistener","caller":"sink/sink.go:144","msg":"failed to ApplyEventValuesToParams: &{%!w(string=failed to replace JSONPath value for param bucket: {string $(body.taskRun.spec.outputs.resources[?(@.name == 'bucket')].resourceRef.name) []}: &{%!w(string=unterminated filter)})}","knative.dev/controller":"eventlistener","/triggers-eventid":"958bw","/trigger":"log-collection","stacktrace":"github.com/tektoncd/triggers/pkg/sink.Sink.processTrigger\n\t/workspace/go/src/github.com/tektoncd/triggers/pkg/sink/sink.go:144\ngithub.com/tektoncd/triggers/pkg/sink.Sink.HandleEvent.func1\n\t/workspace/go/src/github.com/tektoncd/triggers/pkg/sink/sink.go:93"}
```

**Comment by afrittoli** [comment]
The upgrade to v0.2.1-preview fixed the issue, but now it's broken again

**Comment by vdemeester** [comment]
Yeah :sweat:

**Comment by afrittoli** [comment]
The log is there in the previous folder, but not in the latest one. This will require some extra logic in the task.

**Comment by afrittoli** [comment]
The log has been missing for a while, this is still an issue.
