### ISSUE TITLE
Replace Boskos StatefulSet with Deployment

### ISSUE THREAD

**Issue by bobcatfish** [tektoncd/plumbing#193]
# Expected Behavior

If you make changes to the boskos configuration and apply it, you should be able to see the changes in the resulting pod.

# Actual Behavior

The boskos StatefulSet has update strategy "ondelete" so you have to delete the pod before it'll get the update.

# Steps to Reproduce the Problem

1. Change the image in boskos/boskos.yaml
2. Apply the config
3. Watch nothing happen

# Additional Info

The k8s prow folks seem to have gone through this same cycle https://github.com/kubernetes/test-infra/issues/11956 and are now using a Deployment (and they got rid of the PVC as well) https://github.com/kubernetes/test-infra/pull/13594/files

**Comment by afrittoli** [comment]
@bobcatfish is this something we still need to fix?

**Comment by bobcatfish** [comment]
@afrittoli yeah, esp. since it looks like we're for sure going to be using boskos in the future. @tomgeorge even has the solution in #225, we just need to verify that it works. I can add this to my todo list!

**Comment by bobcatfish** [comment]
feels like something we should do but if it's not important enough then maybe it's not worth it
