### ISSUE TITLE
Configure the github release task to use a functional user

### ISSUE THREAD

**Issue by afrittoli** [tektoncd/plumbing#196]
# Expected Behavior
When drafting a GitHub release using the `create-draft-release` task, the release should be created with the token of a functional user.

# Actual Behavior
It is created using @afrittoli token.

**Comment by vdemeester** [comment]
We should have a tekton-robot account for those, with a robot-cat avatar :stuck_out_tongue_closed_eyes: 

/kind feature
/area test-infra
/area dogfooding

**Comment by vdemeester** [comment]
@bobcatfish @afrittoli do we have a tekton-robot account ? 
- if yes who has access so we can create tokens for it (releases, …)
- if no, we should create one and share access (governance member)

**Comment by afrittoli** [comment]
I believe there's a `tekton-robot` account that is used by prow, but I don't have access to its credentials. We will need an account to create releases, run CI jobs etc - we could use the same as prow or we could have a different one.

**Comment by afrittoli** [comment]
The `github-token` secret now contains a token from the `tekton-robot` account.
