### ISSUE TITLE
Add a Tekton based check to enforce a `kind` label

### ISSUE THREAD

**Issue by afrittoli** [tektoncd/plumbing#206]
# Expected Behavior
To help release automation, it should not be possible to merge a PR if it doesn't have a "kind" label set. 

# Implementation plan
Create a new trigger that listens for PR changes.
Create a task that fetches the list of labels, if zero or more then one are found the check is failed.
Update the PR from the task with check passed or failed - and instructions on how to add a label if it's missing.

**Comment by bobcatfish** [comment]
Failed comment could provide docs on what options can be used:

https://github.com/tektoncd/plumbing/blob/5ad2abad9a33c16496c9c2bce6a4d2a6db2d7250/label_sync/labels.yaml#L81-L122

**Comment by bobcatfish** [comment]
I think this was fixed via https://github.com/tektoncd/plumbing/pull/229 anyway!

**Comment by afrittoli** [comment]
> I think this was fixed via #229 anyway!

Indeed!
