### ISSUE TITLE
Tag catalog repository on pipeline release

### ISSUE THREAD

**Issue by chmouel** [tektoncd/plumbing#210]
When we do a major pipeline release it would be useful to tag the [tektoncd/catalog](github.com/tektoncd/catalog) repository.

/cc @sthaha 

/assign

**Comment by afrittoli** [comment]
@chmouel Do you have any proposal for the format of the tags?
Would it be something like pipeline-vX.Y.Z or triggers-vX.Y.Z?
What would the presence of the tag actually mean? As things are today I don't think we are in a position to guarantee that all resources in the catalog work on the tagged version?

**Comment by vdemeester** [comment]
Related catalog issue : https://github.com/tektoncd/catalog/issues/96

**Comment by chmouel** [comment]
on our downstream releases we have used a simple mechanism : 

if there is a pipeline major release of 0.10.0 we tag pipeline on release-0.10 and catalog to release-0.10  (so matching it) if there is a minor release we don't tag them..

in retrospective we should probably name the tag `pipeline-0.10` for catalogs as this could be less confusing. 

we don't (yet) do this on triggers, I don't know (since it's a new prooject) what is the support assumption for triggers is only the latest triggers support the  latest pipeline release? I think we may have to discuss this with the triggers team..

As for CLI, we don't do any tagging, since we assume that CLI should be compatible with -2 version (but unfortunately not gating for that yet).
