### ISSUE TITLE
Isolate certain Pipeline examples into their own namespace

### ISSUE THREAD

**Issue by sbwsg** [tektoncd/plumbing#217]
# Desirable Behavior

A couple of the examples we have in Pipeline need to run in their own namespace in order to test them without leaking some state into other running examples.  [Specifically the LimitRangeName examples](https://github.com/tektoncd/pipeline/pull/2004) which currently have to live under a `no-ci` directory so they don't run.  If run in the same namespace as other examples they will cause some minor explosions that prevent the PR from passing checks.

So it'd be desirable for the examples to either choose their own namespace name (using whatever default that is used currently if they don't specify one) OR we could run each example in its own tiny namespace that gets torn down after it finishes.

**Comment by sbwsg** [comment]
I'm actually not totally sure if this belongs in Plumbing or Pipelines.  Sorry if this is the wrong place :S

**Comment by danielhelfand** [comment]
Would there be anything that prevents examples from creating a namespace and then just specifying that the resources should be created in the namespace that is part of the example?

**Comment by sbwsg** [comment]
interesting.  So they'd include a namespace document as part of their yaml?  The only issue I could see there is collisions if multiple test runs are going at once.  Does that happen?  I'm not clear.

**Comment by danielhelfand** [comment]
> interesting. So they'd include a namespace document as part of their yaml? 

Yes, so add in a namespace to the YAML and have the resources be created in the namespace. It could get a bit unorganized as far as maintaining, but perhaps it could be reserved for specific cases.

> The only issue I could see there is collisions if multiple test runs are going at once. Does that happen? I'm not clear.

It's a good question. I'm not familiar with exactly what is done for integration testing as far as infrastructure. What is provided for each pull request when integration tests are run?

**Comment by sbwsg** [comment]
> What is provided for each pull request when integration tests are run?

OK I think I was way off base with my last comment.  It looks like we spin up a completely fresh cluster for each integration test run (or, rather, Boskos does this).  So using a namespace won't collide I don't think.  :+1:
