### ISSUE TITLE
Release pipelines should pin their image versions

### ISSUE THREAD

**Issue by AlanGreene** [tektoncd/plumbing#2197]
All nightly releases started failing on September 19th due to an issue with the `koparse` image, see fix in https://github.com/tektoncd/plumbing/pull/2196

The nightly releases picked up the bad image as they were using the `latest` tag.

All images should be pinned using an appropriate image digest to ensure repeatable builds and to avoid picking up unexpected changes. From a quick review of the first few nightly releases many projects are using the `latest` tag of at least the `ko`, `ko-gcloud`, and `koparse` images.

List of releases in the `tekton-nightly` namespace:
- [x] add-pr-body [runs](https://dashboard.dogfooding.tekton.dev/#/namespaces/tekton-nightly/pipelineruns?labelSelector=tekton.dev%2Fpipeline%3Dadd-pr-body-release), [definition](https://github.com/tektoncd/plumbing/tree/main/tekton/ci/interceptors/add-pr-body/tekton) https://github.com/tektoncd/plumbing/pull/2203
- [x] add-pr-body-ci [runs](https://dashboard.dogfooding.tekton.dev/#/namespaces/tekton-nightly/pipelineruns?labelSelector=tekton.dev%2Fpipeline%3Dadd-pr-body-ci-release), [definition](https://github.com/tektoncd/plumbing/tree/main/tekton/ci/interceptors/add-pr-body/tekton) https://github.com/tektoncd/plumbing/pull/2203
- [x] add-team-members [runs](https://dashboard.dogfooding.tekton.dev/#/namespaces/tekton-nightly/pipelineruns?labelSelector=tekton.dev%2Fpipeline%3Dadd-team-members-release), [definition](https://github.com/tektoncd/plumbing/tree/main/tekton/ci/interceptors/add-team-members/tekton) https://github.com/tektoncd/plumbing/pull/2204
- [x] cel [runs](https://dashboard.dogfooding.tekton.dev/#/namespaces/tekton-nightly/pipelineruns?labelSelector=tekton.dev%2Fpipeline%3Dcel-release), [definition](https://github.com/tektoncd/experimental/tree/main/cel/tekton) https://github.com/tektoncd/experimental/pull/977
- [x] chains [runs](https://dashboard.dogfooding.tekton.dev/#/namespaces/tekton-nightly/pipelineruns?labelSelector=tekton.dev%2Fpipeline%3Dchains-chains-release), [definition](https://github.com/tektoncd/chains/tree/main/release) https://github.com/tektoncd/chains/pull/1215
- [x] cloudevents [runs](https://dashboard.dogfooding.tekton.dev/#/namespaces/tekton-nightly/pipelineruns?labelSelector=tekton.dev%2Fpipeline%3Dcloudevents-release), [definition](https://github.com/tektoncd/experimental/tree/main/cloudevents/tekton) https://github.com/tektoncd/experimental/pull/978
- [x] concurrency [runs](https://dashboard.dogfooding.tekton.dev/#/namespaces/tekton-nightly/pipelineruns?labelSelector=tekton.dev%2Fpipeline%3Dconcurrency-release), [definition](https://github.com/tektoncd/experimental/tree/main/tekton) https://github.com/tektoncd/experimental/pull/973
- [x] dashboard [runs](https://dashboard.dogfooding.tekton.dev/#/namespaces/tekton-nightly/pipelineruns?labelSelector=tekton.dev%2Fpipeline%3Ddashboard-dashboard-release), [definition](https://github.com/tektoncd/dashboard/tree/main/tekton) https://github.com/tektoncd/dashboard/pull/3622
- [x] operator [runs](https://dashboard.dogfooding.tekton.dev/#/namespaces/tekton-nightly/pipelineruns?labelSelector=tekton.dev%2Fpipeline%3Doperator-operator-release), [definition](https://github.com/tektoncd/operator/tree/main/tekton) https://github.com/tektoncd/operator/pull/2350
- [x] pipeline-in-pod [runs](https://dashboard.dogfooding.tekton.dev/#/namespaces/tekton-nightly/pipelineruns?labelSelector=tekton.dev%2Fpipeline%3Dpipeline-in-pod-release), [definition](https://github.com/tektoncd/experimental/tree/main/tekton) https://github.com/tektoncd/experimental/pull/973
- [x] pipeline-to-taskrun [runs](https://dashboard.dogfooding.tekton.dev/#/namespaces/tekton-nightly/pipelineruns?labelSelector=tekton.dev%2Fpipeline%3Dpipeline-to-taskrun-release), [definition](https://github.com/tektoncd/experimental/tree/main/pipeline-to-taskrun/tekton) https://github.com/tektoncd/experimental/pull/976
- [x] pipelines [runs](https://dashboard.dogfooding.tekton.dev/#/namespaces/tekton-nightly/pipelineruns?labelSelector=tekton.dev%2Fpipeline%3Dpipeline-pipeline-release), [definition](https://github.com/tektoncd/pipeline/tree/main/tekton) https://github.com/tektoncd/pipeline/pull/8287
- [x] pipelines-in-pipelines [runs](https://dashboard.dogfooding.tekton.dev/#/namespaces/tekton-nightly/pipelineruns?labelSelector=tekton.dev%2Fpipeline%3Dpipelines-in-pipelines-release), [definition](https://github.com/tektoncd/experimental/tree/main/pipelines-in-pipelines/tekton) https://github.com/tektoncd/experimental/pull/975
- [x] pr-commenter [runs](https://dashboard.dogfooding.tekton.dev/#/namespaces/tekton-nightly/pipelineruns?labelSelector=tekton.dev%2Fpipeline%3Dpr-commenter-release), [definition](https://github.com/tektoncd/plumbing/tree/main/tekton/ci/custom-tasks/pr-commenter/tekton) https://github.com/tektoncd/plumbing/pull/2205
- [x] pr-status-updater [runs](https://dashboard.dogfooding.tekton.dev/#/namespaces/tekton-nightly/pipelineruns?labelSelector=tekton.dev%2Fpipeline%3Dpr-status-updater-release), [definition](https://github.com/tektoncd/plumbing/tree/main/tekton/ci/custom-tasks/pr-status-updater/tekton) https://github.com/tektoncd/plumbing/pull/2205
- [x] task-loops [runs](https://dashboard.dogfooding.tekton.dev/#/namespaces/tekton-nightly/pipelineruns?labelSelector=tekton.dev%2Fpipeline%3Dtask-loops-release), [definition](https://github.com/tektoncd/experimental/tree/main/task-loops/tekton) https://github.com/tektoncd/experimental/pull/974
- [x] triggers [runs](https://dashboard.dogfooding.tekton.dev/#/namespaces/tekton-nightly/pipelineruns?labelSelector=tekton.dev%2Fpipeline%3Dtriggers-triggers-release), [definition](https://github.com/tektoncd/triggers/tree/main/tekton) https://github.com/tektoncd/triggers/pull/1767
- [x] wait-task [runs](https://dashboard.dogfooding.tekton.dev/#/namespaces/tekton-nightly/pipelineruns?labelSelector=tekton.dev%2Fpipeline%3Dwait-task-release), [definition](https://github.com/tektoncd/experimental/tree/main/wait-task/tekton) https://github.com/tektoncd/experimental/pull/972
- [x] workflows [runs](https://dashboard.dogfooding.tekton.dev/#/namespaces/tekton-nightly/pipelineruns?labelSelector=tekton.dev%2Fpipeline%3Dworkflows-release), [definition](https://github.com/tektoncd/experimental/tree/main/tekton) https://github.com/tektoncd/experimental/pull/973

Taking the most recent one as an example, these are the unpinned images used, most are using `latest`:

## wait-task

- [nightly release PipelineRuns](https://dashboard.dogfooding.tekton.dev/#/namespaces/tekton-nightly/pipelineruns?labelSelector=tekton.dev%2Fpipeline%3Dwait-task-release)
- [release pipeline definition](https://github.com/tektoncd/experimental/tree/main/wait-task/tekton)

| task | step | image |
|------|------|-------|
| git-clone | clone | gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/git-init:v0.18.1 (should specify digest too) |
| unit-tests | unit-test | docker.io/library/golang:latest |
| build-tests | build | docker.io/library/golang:latest |
| publish-images | create-ko-yaml | busybox |
| publish-images | container-registry-auth | gcr.io/go-containerregistry/crane:debug |
| publish-images | run-ko | gcr.io/tekton-releases/dogfooding/ko:latest |
| publish-images | koparse | gcr.io/tekton-releases/dogfooding/koparse:latest |
| publish-images | tag-images | gcr.io/go-containerregistry/crane:debug |
| report-bucket | create-results | alpine |

**Comment by AlanGreene** [comment]
Dashboard and Pipelines nightly releases are passing again, updated to use the latest `koparse` image, and now publishing their images to ghcr.io.

Andrea also has a PR open against tektoncd/triggers to update it to the latest `koparse` and move to ghcr.io.

PRs open for other services, tasks, etc. to pin images to known working state.

**Comment by AlanGreene** [comment]
Triggers nightly release is passing again, also updated to the latest `koparse` image and publishing images to ghcr.io

The following nightly releases are also passing again:
- cloudevents
- concurrency
- pipeline-in-pod
- pipeline-to-taskrun
- pipelines-in-pipelines
- task-loops
- wait-task

Chains nightly is failing due to a known bad test: https://github.com/tektoncd/chains/issues/1178

`cel` nightly is failing due to wrong go version:
```
2024-09-27T02:08:39.542964111Z Error: error processing import paths in "/workspace/go/src/github.com/tektoncd/experimental/cel/config/500-controller.yaml": error resolving image references: build: go build: exit status 1: # [golang.org/x/sys/unix](http://golang.org/x/sys/unix)
2024-09-27T02:08:39.543058620Z vendor/golang.org/x/sys/unix/syscall.go:83:16: unsafe.Slice requires go1.17 or later (-lang was set to go1.16; check go.mod)
```

`add-team-members`, `add-pr-body`, and `add-pr-body-ci` nightly are failing due to missing task:
```
Pipeline tekton-nightly/add-team-members-release can't be Run; it contains Tasks that don't exist: Couldn't retrieve Task "": error requesting remote resource: error getting "bundleresolver" "tekton-nightly/bundles-c741b1a1ad5c6d7d07337a952fbd7d6a": could not find object in image with kind: task and name: git-batch-merge
```

`pr-commenter` failing due to:
```
2024-09-27T00:01:06.270600691Z go: updates to go.mod needed; to update it:
2024-09-27T00:01:06.270635326Z 	go mod tidy
```

**Comment by afrittoli** [comment]
Fix for the CEL component: https://github.com/tektoncd/experimental/pull/979

**Comment by afrittoli** [comment]
Remaining issues:

* `pr-commenter`:
```
+ IMAGES=' [gcr.io/tekton-nightly/github.com/tektoncd/plumbing/tekton/ci/custom-tasks/pr-commenter/cmd/pr-commenter:v20241003-d627097ada](http://gcr.io/tekton-nightly/github.com/tektoncd/plumbing/tekton/ci/custom-tasks/pr-commenter/cmd/pr-commenter:v20241003-d627097ada)'
/tekton/scripts/script-3-bmfdd: line 19: syntax error: unterminated quoted string
```

* `add-pr-body`:
```
+ IMAGES_PATH=[gcr.io/tekton-nightly/github.com/tektoncd/plumbing](http://gcr.io/tekton-nightly/github.com/tektoncd/plumbing)
+ '[' tekton/ci/interceptors/add-pr-body '!='  ]
+ IMAGES_PATH=[gcr.io/tekton-nightly/github.com/tektoncd/plumbing/tekton/ci/interceptors/add-pr-body](http://gcr.io/tekton-nightly/github.com/tektoncd/plumbing/tekton/ci/interceptors/add-pr-body)
+ IMAGES=' [gcr.io/tekton-nightly/github.com/tektoncd/plumbing/tekton/ci/interceptors/add-pr-body/cmd/add-pr-body:v20241003-d627097ada](http://gcr.io/tekton-nightly/github.com/tektoncd/plumbing/tekton/ci/interceptors/add-pr-body/cmd/add-pr-body:v20241003-d627097ada)'
+ koparse --path /workspace/output/v20241003-d627097ada/release.yaml --base [gcr.io/tekton-nightly/github.com/tektoncd/plumbing/tekton/ci/interceptors/add-pr-body](http://gcr.io/tekton-nightly/github.com/tektoncd/plumbing/tekton/ci/interceptors/add-pr-body) --images [gcr.io/tekton-nightly/github.com/tektoncd/plumbing/tekton/ci/interceptors/add-pr-body/cmd/add-pr-body:v20241003-d627097ada](http://gcr.io/tekton-nightly/github.com/tektoncd/plumbing/tekton/ci/interceptors/add-pr-body/cmd/add-pr-body:v20241003-d627097ada)
Expected images did not match: Images ['[gcr.io/tekton-nightly/github.com/tektoncd/plumbing/tekton/ci/interceptors/add-pr-body/cmd/add-pr-body:v20241003-d627097ada](http://gcr.io/tekton-nightly/github.com/tektoncd/plumbing/tekton/ci/interceptors/add-pr-body/cmd/add-pr-body:v20241003-d627097ada)'] were expected but missing.
```

* `chains`:  still one unit test failing, the new nightly will skip unit tests so it should work once https://github.com/tektoncd/plumbing/pull/2226 is merged

**Comment by afrittoli** [comment]
All remaining issues have been fixed.

**Comment by AlanGreene** [comment]
Thanks for seeing this over the line @afrittoli 🙇  I'll be back next week
