### ISSUE TITLE
Add OCI labels to docker files in `tekton/images`

### ISSUE THREAD

**Issue by afrittoli** [tektoncd/plumbing#2222]
### Feature request

Add standard OCI images to all container files stored under tektoncd/images.
See the [GitHub docs](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry#labelling-container-images) for references on the required labels.

### Use case

This is part of the migration to ghcr.io and https://github.com/tektoncd/plumbing/issues/2157

**Comment by LiteBrick204** [comment]
I would like to work on this.

**Comment by afrittoli** [comment]
Thank you @LiteBrick204. Let me know if you have any question

**Comment by LiteBrick204** [comment]
Is the folder images under tekton or is it in different directory?

**Comment by LiteBrick204** [comment]
and the org.opencontainers.image.source will be the https://github.com/tektoncd/images for all the files?

**Comment by afrittoli** [comment]
No, the source will be the repo where the images are hosted, i.e.
https://github.com/tektoncd/plumbing
