### ISSUE TITLE
Migrate Tekton multi-arch image build to ghcr.io

### ISSUE THREAD

**Issue by afrittoli** [tektoncd/plumbing#2223]
### Feature request

Migrate the [multi-arch-template](https://github.com/tektoncd/plumbing/blob/main/tekton/resources/images/docker-multi-arch-template.yaml) pipeline to publish to ghcr.io. This includes updates to any of the [cronjobs](https://github.com/tektoncd/plumbing/tree/main/tekton/cronjobs/dogfooding/images) that use this template to build images.

**Note**: To be implemented as a separate PR: update references in the `plumbing` repo from gcr.io to ghcr.io once the new images are produced.

The pipeline project [release pipeline](https://github.com/tektoncd/pipeline/blob/main/tekton/publish.yaml) has been migrated and can provide some insight. 

Some key information for the migration:
- Existing path: `gcr.io/tekton-releases/dogfooding/<image-name>`
- Target path: `ghcr.io/tektoncd/plumbing/<image-name>`
- [GitHub requires OCI labels](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry#labelling-container-images) to be set to associate images with the correct GitHub repo, which should be implemented in #2222 

### Use case

Reduce Cloud Storage / Container Registry Spending: https://github.com/tektoncd/plumbing/issues/2157

### Additional Info

- the template part defines the pipeline that is executed to build images
- the cronjobs provide the trigger for the execution of the pipelines, and they include the list of parameters as well as the frequency of execution

The template part needs to be updated so that it may work with ghcr.io. The current version works with gcr.io, and unfortunately, it's not enough to change the target registry as authentication works a bit different (for gcr.io we used a service account file, and for ghcr.io we use a PAT), and ghcr.io requires OCI labels to be set

There are three types of builds we do today, which correspond to three separate templates. 

* Single architecture: https://github.com/tektoncd/plumbing/issues/2221, PLATFORMS and BUILD_TYPE are not set in the cronjob
* Multi-architecture, using docker: https://github.com/tektoncd/plumbing/issues/2223, PLATFORMS is set and BUILD_TYPE=docker
* Multi-architecture, using ko: https://github.com/tektoncd/plumbing/issues/2224, PLATFORMS is set and BUILD_TYPE=ko

This issue covers updating the template and cronjob for multi-architecture, with docker

The order of implementation should be:

- Set the OCI labels in Dockerfiles https://github.com/tektoncd/plumbing/issues/2222
- Adapt the template to work with ghcr.io (see the changes in the pipeline project [release pipeline](https://github.com/tektoncd/pipeline/blob/main/tekton/publish.yaml) for inspiration)
- Adapt the cronjobs (this can be in the same PR as the template or separate)

**Comment by LiteBrick204** [comment]
I would like to work on this.

**Comment by afrittoli** [comment]
@LiteBrick204 that's great, thank you!

**Comment by LiteBrick204** [comment]
@afrittoli for the remaining references in the repo, can I do another PR? Also is the first PR good?

**Comment by afrittoli** [comment]
> Migrate the [single-arch-template](https://github.com/tektoncd/plumbing/blob/main/tekton/resources/images/docker-multi-arch-template.yaml) pipeline to publish to ghcr.io. This includes updates to any of the [cronjobs](https://github.com/tektoncd/plumbing/tree/main/tekton/cronjobs/dogfooding/images) that use this template to build images.

Thank you for the PR! 
Let me provide you with some more details about this:
- the template defines the pipeline that is executed to build images
- the cronjobs provide the trigger for the execution of the pipelines, and they include the list of parameters as well as the frequency of execution

The template part needs to be updated so that it may work with ghcr.io. The current version works with gcr.io, and unfortunately, it's not enough to change the target registry as authentication works a bit different (for gcr.io we used a service account file, and for ghcr.io we use a PAT), and ghcr.io requires OCI labels to be set

I think the order of implementation should be:
- Set the OCI labels in Dockerfiles https://github.com/tektoncd/plumbing/issues/2222
- Adapt the template to work with ghcr.io (see the changes in the pipeline project [release pipeline](https://github.com/tektoncd/pipeline/blob/main/tekton/publish.yaml) for inspiration)
- Adapt the cronjobs, that you started in https://github.com/tektoncd/plumbing/pull/2228

One more note on this. There are three types of builds we do today, which correspond to three separate templates:
- Single architecture: #2221, `PLATFORMS` and `BUILD_TYPE` are not set in the cronjob
- Multi-architecture, using `docker`: #2223, `PLATFORMS` is set and `BUILD_TYPE=docker`
- Multi-architecture, using `ko`: #2224, `PLATFORMS` is set and `BUILD_TYPE=ko`

**Comment by LiteBrick204** [comment]
For the EasyCLA, I am waiting for approval. The site is not going through with it.

**Comment by LiteBrick204** [comment]
Can this be closed since the PR has been merged?
