### ISSUE TITLE
Migrate Tekton ko-multi-arch-template image build to ghcr.io

### ISSUE THREAD

**Issue by afrittoli** [tektoncd/plumbing#2224]
### Feature request

Migrate the [ko-multi-arch-template](https://github.com/tektoncd/plumbing/blob/main/tekton/resources/images/ko-multi-arch-template.yaml) pipeline to publish to ghcr.io. This includes updates to any of the [cronjobs](https://github.com/tektoncd/plumbing/tree/main/tekton/cronjobs/dogfooding/images) that use this template to build images.

**Note**: To be implemented as a separate PR: update references in the `plumbing` repo from gcr.io to ghcr.io once the new images are produced.

The pipeline project [release pipeline](https://github.com/tektoncd/pipeline/blob/main/tekton/publish.yaml). has been migrated and can provide some insight. 

Some key information for the migration:
- Existing path: `gcr.io/tekton-releases/dogfooding/<image-name>`
- Target path: `ghcr.io/tektoncd/plumbing/<image-name>`
- [GitHub requires OCI labels](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry#labelling-container-images) to be set to associate images with the correct GitHub repo, which should be implemented in #2222 

### Use case

Reduce Cloud Storage / Container Registry Spending: https://github.com/tektoncd/plumbing/issues/2157

### Additional Info

- the template part defines the pipeline that is executed to build images
- the cronjobs provide the trigger for the execution of the pipelines, and they include the list of parameters as well as the frequency of execution

The template part needs to be updated so that it may work with ghcr.io. The current version works with gcr.io, and unfortunately, it's not enough to change the target registry as authentication works a bit different (for gcr.io we used a service account file, and for ghcr.io we use a PAT), and ghcr.io requires OCI labels to be set

There are three types of builds we do today, which correspond to three separate templates. 

* Single architecture: https://github.com/tektoncd/plumbing/issues/2221, PLATFORMS and BUILD_TYPE are not set in the cronjob
* Multi-architecture, using docker: https://github.com/tektoncd/plumbing/issues/2223, PLATFORMS is set and BUILD_TYPE=docker
* Multi-architecture, using ko: https://github.com/tektoncd/plumbing/issues/2224, PLATFORMS is set and BUILD_TYPE=ko

This issue covers updating the template and cronjob for multi-architecture, with `ko`

The order of implementation should be:

- Adapt the template to work with ghcr.io (see the changes in the pipeline project [release pipeline](https://github.com/tektoncd/pipeline/blob/main/tekton/publish.yaml) for inspiration). `ko` supports passing OCI label, which should be added in the template
- Adapt the cronjobs (this can be in the same PR as the template or separate)

**Comment by LiteBrick204** [comment]
I would like to work on this.

**Comment by LiteBrick204** [comment]
Can this be closed since the PR has been merged?
