### ISSUE TITLE
Document the setup of the "robocat" cluster

### ISSUE THREAD

**Issue by afrittoli** [tektoncd/plumbing#223]
# Expected Behavior
Everything that is installed in the "robocat" cluster needs to be documented and automated, so that it may be possible to recreate the "robocat" repo from scratch at any time.

The work lays the ground for testing CD of services and configurations, as well as for testing of infra changes. Once we have the cluster setup fully automated, we'll be able to test infra changes by allocating a new cluster, setting it up, and apply the change from the PR.

# Actual Behavior
So far I created the cluster via the cloud console. 
The spec of the cluster shall be documented.

This issue can be considered closed once the documentation structure is done, and the initial setup has been documented. Any extra setup will be handled in dedicated issues.

**Comment by bobcatfish** [comment]
I think we've got this now anyway: https://github.com/tektoncd/plumbing/tree/master/robocat

**Comment by afrittoli** [comment]
Thanks @bobcatfish
