### ISSUE TITLE
Setup monitoring components for infra clusters

### ISSUE THREAD

**Issue by afrittoli** [tektoncd/plumbing#235]
# Expected Behavior

We should monitor the status of the various CI/CD services and we should be able to display metrics about the status of the services using grafana, following the example of 
https://monitoring.prow.k8s.io/d/8P7-1J8Wz/boskos-server-dashboard?orgId=1 and https://github.com/kubernetes/test-infra/tree/201c7788b244ab2fc3efae7249fb939223ef6e1e/prow/cluster/monitoring

Things that we need to monitor are:
- prow and boskos from the `prow` cluster 
- tekton services from the `dogfooding` cluster 

We should display metrics from services where available:
- boskos resource status (e.g. https://monitoring.prow.k8s.io/d/wSrfvNxWz/boskos-resource-usage?orgId=1)
- tekton pipelinerun and taskrun metrics 

We'll need prometheus and grafana deployed somewhere. 
We may be able to use one instance across clusters, at least for grafana.
We might want alertmanager too, so we could alert build-cop on slack when something is broken.

# Actual Behavior
We don't have any monitoring in place

**Comment by bobcatfish** [comment]
Great idea!

**Comment by bobcatfish** [comment]
I'm gonna tentatively assign this to myself, since i'm looking into https://github.com/tektoncd/pipeline/issues/540 theoretically ill at least look into setting up some monitoring for performance testing, maybe!

/assign
