### ISSUE TITLE
label_sync did not add area/buildpacks to tektoncd/catalog

### ISSUE THREAD

**Issue by jromero** [tektoncd/plumbing#243]
# Expected Behavior
Based on the PR https://github.com/tektoncd/plumbing/pull/203 we would expect a label `area/buildpacks` to exist in the tektoncd/catalog repo yet that is not the case.

# Actual Behavior

No such label exists.

See https://github.com/tektoncd/catalog/labels?q=buildpacks

**Comment by vdemeester** [comment]
@jromero manually fixed it and create #244 for making sure it doesn't require a manual intervention :angel:
