### ISSUE TITLE
Automate config.yaml prow configuration

### ISSUE THREAD

**Issue by vdemeester** [tektoncd/plumbing#25]
The [`prow/config.yaml`](./prow/config.yaml) is getting bigger and bigger — but lot's of configuration share the same content. We may want to have a smaller configuration file that we use to generate the *final* `config.yaml`.

Inspiration comes from [`knative/test-infra`](https://github.com/knative/test-infra/blob/master/ci/prow/make_config.go)

/kind question

**Comment by bobcatfish** [comment]
I'm tempted to suggest we wait until we have converted more of our jobs to Tekton jobs (https://github.com/tektoncd/pipeline/issues/922) what do you think @vdemeester ?

**Comment by vdemeester** [comment]
I think yes :angel: let's focus on dogfooding :dancer:

**Comment by vdemeester** [comment]
Let's close this one for now then :angel: 

/close
