### ISSUE TITLE
Automate and share labels accross repositories

### ISSUE THREAD

**Issue by vdemeester** [tektoncd/plumbing#26]
So, to integrate better with `tide` and, for example, letting users/contriubtors add some labels to their issues, we need some specific labels (e.g. `question` -> `kind/question`, …) — I am refering to [`tide` commands](https://prow.tekton.dev/command-help).

- We could use https://github.com/kubernetes/test-infra/tree/master/label_sync (with our own configuration and colors :catdance: ) or https://github.com/icecrime/label-all-the-things for automating that
- We need to define the list we want (for `kind/…`, `area/…`, `priority/…`, etc.) and store this configuration here

cc @bobcatfish @abayer @dlorenc 

/assign
/kind enhancement

**Comment by bobcatfish** [comment]
Seems like a good idea to me!
