### ISSUE TITLE
Helm chart

### ISSUE THREAD

**Issue by eddycharly** [tektoncd/plumbing#278]
I'm using a helm chart i wrote to deploy Tekton for a few months now and it's working great.

Would you be interested in a contribution for this ?

**Comment by afrittoli** [comment]
@eddycharly thanks, I think it would be a nice idea. We do have an operator already, but there's a whole ecosystem of people that uses prominently helm, so it would be good. 
Would you be interested in maintaining it and documenting it - at least until more contributors come along? What does it take to host an helm chart repo where people could download the chart from?

**Comment by eddycharly** [comment]
Sure, i will be happy to maintain it.
Technical documentation is already available as it is generated with helm-docs.

I also have a couple of prow jobs to help releasing new versions of the chart.

On the hosting side, it can be as easy as putting a tar.gz and index.yaml in a bucket. That's the easiest solution, another option is to use [chartmuseum](https://github.com/helm/charts/tree/master/stable/chartmuseum).

I currently chartmuseum because it hosted on a private chart repository but for public charts, there's nothing better than the bucket solution i guess.

**Comment by eddycharly** [comment]
I'll try to open a PR today or tomorrow, it will be easier to discuss about it.

**Comment by afrittoli** [comment]
OK - thank you. Would you like to add the PR to the experimental repo?
If we decide to host this, I think it might go into a dedicated repo.

**Comment by eddycharly** [comment]
Ok for the experimental repo.
It will start the discussion, if you want to put it somewhere else i will close the PR and open another one on the target repo.

**Comment by eddycharly** [comment]
I opened a PR with some WIP here https://github.com/tektoncd/experimental/pull/494

I started with a copy of my helm chart and took the opportunity to rewrite/improve a few things.
I hope it's a good starting point.

**Comment by eddycharly** [comment]
Thinking about a versioning policy for helm charts.

A good approach would be to use the same major and minor version as the target Tekton component, keeping the patch to increment on bug fixes.

In any case, the `appVersion` in the chart description should be the full target component version.

Ok for you ?

**Comment by eddycharly** [comment]
Closing. Too broad. More relevant issues exist in the experimental repo.
