### ISSUE TITLE
Needs Rebase Notification for Pull Requests

### ISSUE THREAD

**Issue by danielhelfand** [tektoncd/plumbing#286]
Not sure if this is the appropriate place to open this/if there have already been discussions somewhere else. 

# Expected Behavior

Similar to what is done for Kubernetes, there should be an automatic notification when a pull request for Tekton projects needs a rebase and the needs-rebase label should be applied to the pr. Upon successfully resolving conflicts, the label should be removed from the pr. 

This will help to inform contributors about a needed rebase so they don't have to check prs to discover the issue.

# Actual Behavior

There isn't a notification when a pull request needs a rebase.

/kind feature
/kind question

**Comment by afrittoli** [comment]
We could write a check for that.. unless there is already a github app for that.

**Comment by afrittoli** [comment]
This is not implemented through the prow rebase plugin. Is it ok to close?

**Comment by vdemeester** [comment]
I think it is :wink:
