### ISSUE TITLE
Github project automation not working as expected :O

### ISSUE THREAD

**Issue by bobcatfish** [tektoncd/plumbing#293]
# Expected Behavior

New issues added to pipeline tekton project (https://github.com/orgs/tektoncd/projects/3)  which are linked (pipeline, community, plumbing) should how up in the "needs triage" column, other projects should not.

# Actual Behavior

We are trying to use  https://github.com/philschatz/project-bot  but:

* Not all issues are automatically added to the project (e.g. i added https://github.com/tektoncd/pipeline/issues/2272 manually)
* Issues do not appear in "need triage", even tho we have a card that should make it work:
![image](https://user-images.githubusercontent.com/432502/78279147-17920600-74e5-11ea-9454-ddcefb13a049.png)
* Issues from non-linked projects appear on the board e.g.:
![image](https://user-images.githubusercontent.com/432502/78279219-36909800-74e5-11ea-8e1f-a875cd0274ad.png) 
![image](https://user-images.githubusercontent.com/432502/78279257-44461d80-74e5-11ea-9c3e-94078727fff2.png)

**Comment by bobcatfish** [comment]
I wonder if having the same repo linked in multiple projects causes race conditions with `project-bot`:

![image](https://user-images.githubusercontent.com/432502/78279543-aef75900-74e5-11ea-912e-6fc73ede4d6e.png)

**Comment by bobcatfish** [comment]
> I wonder if having the same repo linked in multiple projects causes race conditions with project-bot

That would probably make more sense if we could see that the issues that werent showing up in "needs triage" were showing up in other projects, but at least in these 2 issues that isnt the case:

* https://github.com/tektoncd/pipeline/issues/2316
* https://github.com/tektoncd/plumbing/issues/291

**Comment by vdemeester** [comment]
arf… :sweat: 
/kind bug
