### ISSUE TITLE
Run helm lint on tektoncd/experimental helm charts

### ISSUE THREAD

**Issue by eddycharly** [tektoncd/plumbing#306]
# Expected Behavior

`tektoncd/experimental` pull requests should not be merged if helm charts don't pass helm linter.
We should add a helm lint prow job on `tektoncd/experimental` pull requests.

# Actual Behavior

No job to check helm charts through helm linter.

**Comment by vdemeester** [comment]
@eddycharly I guess we can close this ?

/kind feature

**Comment by eddycharly** [comment]
@eddycharly linting  the operator chart is not there as the operator chart is not finished yet.

This will take some time though as there is no operator official release, a few things must be done before having a chart.

You can close it if you want i will create dedicated issues when needed.
