### ISSUE TITLE
Ensure helm docs on tektoncd/experimental helm charts are up to date

### ISSUE THREAD

**Issue by eddycharly** [tektoncd/plumbing#309]
# Expected Behavior

`tektoncd/experimental` pull requests should not be merged if docs for helm charts are not up to date.
We should add a helm docs verification prow job on `tektoncd/experimental` pull requests.

# Actual Behavior

No job to check helm docs are up to date.

**Comment by vdemeester** [comment]
@eddycharly can we close this issue or is there still work to do ?

/kind feature

**Comment by eddycharly** [comment]
This is up and running.
/close
