### ISSUE TITLE
images: share the same base image (debian vs alpine)

### ISSUE THREAD

**Issue by vdemeester** [tektoncd/plumbing#335]
We should ensure all the image we use for our ci / cd share the same base image (`tekton/images` but potentially others).

- They would share the common layers (potentially reducing storage consumption — not a big deal)
- It makes them all consistent (aka same set of commands to install a package, …)

I would vote for `debian` mainly because `alpine` has `musl` instead of `libc` and that can be a problem in certain cases. The base debian image in not that big *and* if all the image share the same base, the footprint (storage and memory) is not that big either.

/kind feature
/kind question
/area dogfooding

**Comment by dibyom** [comment]
+1 for using debian everywhere!
