### ISSUE TITLE
ko failing to publish nightly image

### ISSUE THREAD

**Issue by bobcatfish** [tektoncd/plumbing#370]
pipeline-release-nightly-w9cjw failed in the dogfood cluster last night, specifically pipeline-release-nightly-w9cjw-publish-images-krlpp failed with:

```
[run-ko] 2020/05/04 02:09:24 Using base gcr.io/distroless/static:latest for github.com/tektoncd/pipeline/cmd/kubeconfigwriter
[run-ko] 2020/05/04 02:09:26 Building github.com/tektoncd/pipeline/vendor/github.com/GoogleCloudPlatform/cloud-builders/gcs-fetcher/cmd/gcs-fetcher
[run-ko] 2020/05/04 02:09:26 Building github.com/tektoncd/pipeline/cmd/kubeconfigwriter
[run-ko] 2020/05/04 02:09:34 Using base gcr.io/distroless/static:latest for github.com/tektoncd/pipeline/cmd/imagedigestexporter
[run-ko] 2020/05/04 02:09:34 Unexpected error running "go build": signal: killed
[run-ko] 2020/05/04 02:09:34 Unexpected error running "go build": signal: killed
[run-ko] 2020/05/04 02:09:35 Building github.com/tektoncd/pipeline/cmd/imagedigestexporter
[run-ko] 2020/05/04 02:09:35 Unexpected error running "go build": context canceled
[run-ko] 2020/05/04 02:09:35 error processing import paths in "/workspace/go/src/github.com/tektoncd/pipeline/config/webhook.yaml": error resolving image references: repository can only contain the runes `abcdefghijklmnopqrstuvwxyz0123456789_-./`: tekton-nightly/ko://github.com/tektoncd/pipeline/cmd/webhook

```

**Comment by bobcatfish** [comment]
Here are the logs going a bit further back:

```
[run-ko] + ko resolve --preserve-import-paths -t v20200504-7bbc7ebf3b -f /workspace/go/src/github.com/tektoncd/pipeline/config/
[run-ko] 2020/05/04 02:05:54 Using base gcr.io/distroless/static:latest for github.com/tektoncd/pipeline/cmd/webhook
[run-ko] 2020/05/04 02:05:54 Using base gcr.io/distroless/static:latest for github.com/tektoncd/pipeline/cmd/pullrequest-init
[run-ko] 2020/05/04 02:05:54 Using base gcr.io/tekton-nightly/github.com/tektoncd/pipeline/build-base:latest for github.com/tektoncd/pipeline/cmd/creds-init
[run-ko] 2020/05/04 02:05:54 Using base busybox for github.com/tektoncd/pipeline/cmd/entrypoint
[run-ko] 2020/05/04 02:05:55 Building github.com/tektoncd/pipeline/cmd/pullrequest-init
[run-ko] 2020/05/04 02:05:55 Building github.com/tektoncd/pipeline/cmd/entrypoint
[run-ko] 2020/05/04 02:05:55 Building github.com/tektoncd/pipeline/cmd/webhook
[run-ko] 2020/05/04 02:05:55 Building github.com/tektoncd/pipeline/cmd/creds-init
[run-ko] 2020/05/04 02:07:09 Using base gcr.io/tekton-nightly/github.com/tektoncd/pipeline/build-base:latest for github.com/tektoncd/pipeline/cmd/git-init
[run-ko] 2020/05/04 02:07:15 Building github.com/tektoncd/pipeline/cmd/git-init
[run-ko] 2020/05/04 02:07:51 Using base gcr.io/distroless/static:latest for github.com/tektoncd/pipeline/cmd/controller
[run-ko] 2020/05/04 02:08:00 Building github.com/tektoncd/pipeline/cmd/controller
[run-ko] 2020/05/04 02:09:24 Using base gcr.io/distroless/static:latest for github.com/tektoncd/pipeline/vendor/github.com/GoogleCloudPlatform/cloud-builders/gcs-fetcher/cmd/gcs-fetcher
[run-ko] 2020/05/04 02:09:24 Using base gcr.io/distroless/static:latest for github.com/tektoncd/pipeline/cmd/kubeconfigwriter
[run-ko] 2020/05/04 02:09:26 Building github.com/tektoncd/pipeline/vendor/github.com/GoogleCloudPlatform/cloud-builders/gcs-fetcher/cmd/gcs-fetcher
[run-ko] 2020/05/04 02:09:26 Building github.com/tektoncd/pipeline/cmd/kubeconfigwriter
[run-ko] 2020/05/04 02:09:34 Using base gcr.io/distroless/static:latest for github.com/tektoncd/pipeline/cmd/imagedigestexporter
[run-ko] 2020/05/04 02:09:34 Unexpected error running "go build": signal: killed
[run-ko] 2020/05/04 02:09:34 Unexpected error running "go build": signal: killed
[run-ko] 2020/05/04 02:09:35 Building github.com/tektoncd/pipeline/cmd/imagedigestexporter
[run-ko] 2020/05/04 02:09:35 Unexpected error running "go build": context canceled
[run-ko] 2020/05/04 02:09:35 error processing import paths in "/workspace/go/src/github.com/tektoncd/pipeline/config/webhook.yaml": error resolving image references: repository can only contain the runes `abcdefghijklmnopqrstuvwxyz0123456789_-./`: tekton-nightly/ko://github.com/tektoncd/pipeline/cmd/webhook
```

I wonder if the process is getting starved, and getting OOM-killed or timing out 🤔

**Comment by bobcatfish** [comment]
I thought maybe it was because we were running so many builds at once, but none of the other builds that start at the same time are showing any sign of going too slowly or being overloaded.

**Comment by vdemeester** [comment]
Looking at the logs, yeah it got OOM-killed or something along those lines.
/kind bug

**Comment by bobcatfish** [comment]
Running manually to see what happens:

```
 k --context dogfood create job --from cronjob/nightly-cron-trigger-pipeline-nightly-release nightly-cron-trigger-pipeline-nightly-release-manual-05042020
```

**Comment by bobcatfish** [comment]
Same thing happened again, in the same way, which seems suspicious:

```
peline/cmd/creds-init
[run-ko] 2020/05/04 14:00:31 Building github.com/tektoncd/pipeline/cmd/entrypoint
[run-ko] 2020/05/04 14:00:31 Building github.com/tektoncd/pipeline/cmd/controller
[run-ko] 2020/05/04 14:00:32 Building github.com/tektoncd/pipeline/cmd/creds-init
[run-ko] 2020/05/04 14:00:41 Using base gcr.io/distroless/static:latest for github.com/tektoncd/pipeline/cmd/pullrequest-init
[run-ko] 2020/05/04 14:00:43 Building github.com/tektoncd/pipeline/cmd/pullrequest-init
[run-ko] 2020/05/04 14:00:47 Unexpected error running "go build": signal: killed
[run-ko] 2020/05/04 14:00:47 Unexpected error running "go build": signal: killed
[run-ko] 2020/05/04 14:00:48 error processing import paths in "/workspace/go/src/github.com/tektoncd/pipeline/config/webhook.yaml": error resolving image references: repository can only contain the runes `abcdefghijklmnopqrstuvwxyz0123456789_-./`: tekton-nightly/ko://github.com/tektoncd/pipeline/cmd/webhook
```

I wonder if the kill signals are just indications that ko is bailing and its cancelling other things in progress. Note this time there are no multi-minute gaps between output 🤔

**Comment by bobcatfish** [comment]
Ah okay, I get the same problem locally when using ko from head, the image was using `v0.4.1-0.20200504014251-d45c52775002` installed via `go get github.com/google/ko/cmd/ko@master`

```
2020/05/04 10:57:30 error processing import paths in "config/webhook.yaml": error resolving image references: repository can only contain the runes `abcdefghijklmnopqrstuvwxyz0123456789_-./`: christiewilson-catfactory/ko://github.com/tektoncd/pipeline/cmd/webhook
```

Might be a ko bug? I think we should probably pin ko.

**Comment by vdemeester** [comment]
@bobcatfish oh nop, this means we need to update some `sed` somewhere in a script :sweat_smile: I wonder why it didn't fail before :thinking: All the import path are prefixed by `ko://`

**Comment by bobcatfish** [comment]
> All the import path are prefixed by ko://

I think they're supposed to be now? https://twitter.com/mattomata/status/1256967648509755393

@mattmoor:

> We want to require the use of `ko://` https://github.com/google/ko/issues/158.  This replaces my "too clever" heuristic with "this one simple trick" from  @ImJasonH. Noooooobody wants to spend more time debugging ImagePullBackoff from http://github.com URLs 😅

**Comment by bobcatfish** [comment]
Ah i see! christiewilson-catfactory is being added before ko:// maybe:

`hristiewilson-catfactory/ko://github.com/tektoncd/pipeline/cmd/webhook`

**Comment by mattmoor** [comment]
This is my bad.  I started passing `ko://` deeper so we could act on it and the default + `-B` both worked, but `-P` got broken :)

Should be fixed here: https://github.com/google/ko/pull/163

**Comment by mattmoor** [comment]
merged and released.  please lmk if you hit anything else

**Comment by bobcatfish** [comment]
Awesome, thanks @mattmoor ! I'll update to pin to the new release.

**Comment by bobcatfish** [comment]
Triggering ko-gcloud image build manually to pick up fixed version of ko:

```
 k --context dogfood create job --from cronjob/image-build-cron-trigger-ko-gcloud image-build-cron-trigger-ko-gcloud-manual-05042020
```

hmm didn't work tho, ko@master seems to get cached somewhere

![image](https://user-images.githubusercontent.com/432502/81010071-b632bf00-8e23-11ea-99f5-6b6c615740a7.png)

**Comment by bobcatfish** [comment]
Hopefully the gcloud-latest image won't get cached on our nodes? 🤔  If we keep seeing this even after we pin ko that might be the problem.

**Comment by bobcatfish** [comment]
Trigger manually now that #371 is merged:

```
 k --context dogfood create job --from cronjob/image-build-cron-trigger-ko-gcloud image-build-cron-trigger-ko-gcloud-manual-05052020
```

**Comment by bobcatfish** [comment]
Looks like it worked and built with 0.5.0! Gonna manually trigger the nightly run now:

```
 k --context dogfood create job --from cronjob/nightly-cron-trigger-pipeline-nightly-release nightly-cron-trigger-pipeline-nightly-release-manual-05052020
```

**Comment by bobcatfish** [comment]
Seems like the same error again but kinda confusing - i suspect image caching. Im gonna try again anyway:

```
k --context dogfood create job --from cronjob/nightly-cron-trigger-pipeline-nightly-release nightly-cron-trigger-pipeline-nightly-release-manual-05052020-2
```

**Comment by bobcatfish** [comment]
Same error still occurring unfortunately!

```
2020/05/05 16:17:47 error processing import paths in "/workspace/go/src/github.com/tektoncd/pipeline/config/webhook.yaml": error resolving image references: repository can only contain the runes `abcdefghijklmnopqrstuvwxyz0123456789_-./`: tekton-nightly/ko://github.com/tektoncd/pipeline/cmd/webhook
```

Theories:

1. the nodes are caching the images, so gcloud-latest isnt being updated. can solve by changing pull policy maybe?
2. i built + pushed the wrong image. either need to find the right image to update, or maybe overnight everyhting will run and it'll fix itself?
3. the image didnt actually pull the fixed ko
4. this didnt actually fix the problem, tho i think it did

**Comment by vdemeester** [comment]
>     1. the nodes are caching the images, so gcloud-latest isnt being updated. can solve by changing pull policy maybe?
If we are using `:latest` it should re-download it all the time (using `:latest` image is similar to the PullAlways policy).
Which image are we using when this fails ? :thinking: 

>     2. i built + pushed the wrong image. either need to find the right image to update, or maybe overnight everyhting will run and it'll fix itself?
The image(s) should rebuild themselves each and every night.

>     3. the image didnt actually pull the fixed ko
>     4. this didnt actually fix the problem, tho i think it did

:unamused:

**Comment by afrittoli** [comment]
Patch on plumbing: https://github.com/tektoncd/plumbing/pull/375

**Comment by afrittoli** [comment]
Patch on pipeline https://github.com/tektoncd/pipeline/pull/2554

**Comment by afrittoli** [comment]
Path on triggers https://github.com/tektoncd/triggers/pull/566

**Comment by afrittoli** [comment]
Patch on dashboard: https://github.com/tektoncd/dashboard/pull/1352

**Comment by bobcatfish** [comment]
Thanks @afrittoli !!!! 🎉
