### ISSUE TITLE
[feature] Create a Tekton based CI job for go linting

### ISSUE THREAD

**Issue by afrittoli** [tektoncd/plumbing#378]
# Expected Behavior
We run the go linter in dedicated CI jobs driven by Tekton

# Actual Behavior
We run the linter as part of the build job in Prow

# Additional Info
This CI job is used by several repositories, so it should be defined in the plumbing repo.
We should use the existing event listener and add a trigger to the list for each repo we want to run the job on. I

This issue can be considered done once we have the job running against one repo (it could be plumbing itself or experimental) and then we can add it to the other repos overtime.

**Comment by danielhelfand** [comment]
I would be interested in picking this up. Assuming this would follow a similar pattern to what was added for [yaml linting](https://github.com/tektoncd/plumbing/pull/336/files)? As far as adding a new Task for go linting, updating the plumbing trigger template with PipelineRun details, and adding a new Pipeline to run?

Would making use of the [go linting task](https://github.com/tektoncd/catalog/blob/8b6c3bf0de24c25af401b79b49af8b7d613889b0/golang/lint.yaml) in the catalog fit here, or is another linter preferred over `golangci-lint`?
