### ISSUE TITLE
Document how tekton dashboard is deployed

### ISSUE THREAD

**Issue by bobcatfish** [tektoncd/plumbing#382]
# Expected Behavior

When build cop and trying to deal with any potential issues related to dashboard not working (e.g. it was down today, turned out it was expected but that's another story!) it should be possibelt o look at the main README in plumbing, and from there navigate to docs and config for the dashboard, both https://dashboard.dogfooding.tekton.dev/ and the robocat dashboard (are they 2 different dashboards?? im not sure)

# Actual Behavior

I didn't see anything helpful in the main readme, so i looked for "dashboard" in the repo and wasn't sure what I should look at. Then I looked for pull requests that mention "dashboard" and found https://github.com/tektoncd/plumbing/pull/276 which seemed helpful but I'm still not sure if that was even the right dashboard.

**Comment by afrittoli** [comment]
Some base documentation on how to do this is available at https://github.com/tektoncd/plumbing/blob/44e1297ae9671074a8aced1c5f6869d85a50f24d/tekton/cd/README.md#L1 - but there is no documentation about how this done specifically for dashboard in `dogfooding` and `robocat`.

**Comment by bobcatfish** [comment]
https://github.com/tektoncd/plumbing/pull/228 probably solves a lot of this also!
