### ISSUE TITLE
[feature] Diversify Cloud Providers for Project Infrastructure

### ISSUE THREAD

**Issue by afrittoli** [tektoncd/plumbing#395]
# Expected Behavior
Tekton runs CI/CD pipelines using cloud resources from different cloud providers

# Actual Behavior
Today all CI/CD pipelines run on GCP/GKE resources.

# Additional Info
Today we run Tekton's CI/CD jobs on Google cloud exclusively, for a couple of reasons:
- the project was born at Google, and we inherited the project infrastructure from there
- several projects in the kubernetes ecosystem (notably kubernets and knative) run their CI on Google cloud, and we inherited infra tools from them.

We are re-writing our project infrastructure so that it uses Tekton to build, test and deploy itself.
In this context it would be beneficial to run pipelines on a diversified infrastructure, including IBM Cloud, AWS and Azure:
- it would help Tekton ensure that we have no hard dependencies in our project infra to a specific cloud provider
- it would help Tekton prove its portability to different clouds when it comes to pushing images to registries, accessing object storage, RBAC
- it would help cloud providers prove their ability to run Tekton and Tekton workloads
- it would help cloud providers further demonstrate their support and commitment to Tekton
- it might motivate more developers to work on the project infrastructure for Tekton - which could benefits from help

Type of workload that we may want to run on different providers:
- nightly releases
- nightly builds and regular deploys
- release / rc release testing
- CI jobs
- more?

**Comment by dlorenc** [comment]
One strategy I've seen is to decouple regular, platform agnostic tests from tests that exercise cloud platform compatibility.

That way you could have one set of tests that can theoretically run anywhere on every PR, then only run the cloud platform ones on PRs that have a reasonable chance of affecting those pass results. 

All e2e tests are flaky, especially ones that require cloud platforms. Multiplying the test matrix by N clouds will make merges harder.

**Comment by afrittoli** [comment]
@dlorenc we could start running periodic jobs against other cloud providers - and if they are stable enough - phase them in into CI.

**Comment by dlorenc** [comment]
Makes sense. So to be clear, we want billing resources with:

- GCP
- IBM Cloud
- Azure
- AWS

Any others?

**Comment by vdemeester** [comment]
Maybe Digital Ocean ? :thinking:
