### ISSUE TITLE
Migrate tektoncd/pipelines Prow checks to Tekton

### ISSUE THREAD

**Issue by bobcatfish** [tektoncd/plumbing#402]
# Expected Behavior

The goal of this issue is to chip away at migrating individual checks that are done with Prow to Tekton.

We also might want to split some of these existing checks up into multiple checks (e.g. the e2e tests do both the "yaml" tests and the end to end tests <-- but they both need a boskos cluster)

# Actual Behavior

These checks currently are handled by Prow:

- [ ] pull-tekton-pipeline-build-tests
- [ ] pull-tekton-pipeline-unit-tests
- [ ] pull-tekton-pipeline-integration-tests
- [ ] pull-tekton-pipeline-go-coverage <-- or replace with a service like coveralls!
- [ ] ci-tekton-pipeline-upgrade-tests (a periodic job)

# Additional Info

* We will also need to be able to trigger these runs manually via a github comment, e.g. `/test <check name>` like we do now with Prow checks
* [Prow config for tekton/pipeline checks](https://github.com/tektoncd/plumbing/blob/master/prow/config.yaml#L747)

**Comment by bobcatfish** [comment]
Feel free to chip away at this one incrementally!

**Comment by vdemeester** [comment]
Updated the title to reflect that it's only on `tektoncd/pipelines`.. will "soon-ish" add issues for the other tektoncd projects :upside_down_face:
