### ISSUE TITLE
Add a new releaser: AlanGreene

### ISSUE THREAD

**Issue by a-roberts** [tektoncd/plumbing#404]
# Expected Behavior
@AlanGreene should also be able to do Tekton Dashboard and Webhooks Extension releases (https://github.com/tektoncd/dashboard/issues/1421 🥳 )

# Actual Behavior
He can't as we've not yet really done anything - when I was added, I think I was added to a certain group on GCP? It lets me create a release secret that's patched to the meow serviceaccount, and I get to modify the bucket contents. Also, this might be a pain since there's a limit of ten secrets and I'm sure we're at ten last time I checked.

**Comment by a-roberts** [comment]
/meow

@bobcatfish @vdemeester can anybody make this happen please? We discussed on the working group call and Vincent suggested an awesome mechanism is in the works but for now we could do things manually 🤞

**Comment by bobcatfish** [comment]
Sorry for the delay! I've taken @AlanGreene 's email from slack and gave him the same permissions as @dibbles in [tekton-releases](https://github.com/tektoncd/plumbing#gcp-projects):

- Service Account Key Admin
- Service Account User
- Storage Object Admin

Let me know if that doesn't do the trick @a-roberts !

Sorry again for not just taking care of that sooner!

**Comment by AlanGreene** [comment]
Thanks @bobcatfish, all sorted now! 😸 
/close
