### ISSUE TITLE
Should we bump the ko image to be 0.5.1 from 0.5.0?

### ISSUE THREAD

**Issue by a-roberts** [tektoncd/plumbing#426]
Hi all, I think w need to update to use ko 0.5.1 to fix a permissions issue that, to cut a long story short, means we can't yet update the katakoda dashboard tutorial to use our 0.7.0 release.

We think it's because the version currently used in the ko gcloud utils image, doesn't have the fix we need. this is the current Dockerfile https://github.com/tektoncd/plumbing/blob/master/tekton/images/ko-gcloud/Dockerfile

Any objections or known gotchas around 0.5.1 first? More context can be found in the Tekton Dashboard channel on our Slack https://tektoncd.slack.com/archives/CHTHGRQBC/p1592250764177000 and I'm wondering if this is gonna break anything.

**Comment by sbwsg** [comment]
oops.

/kind bug

**Comment by AlanGreene** [comment]
I think this can be closed. ko 0.5.0 was re-tagged at some point, but currently shares the same commit sha as 0.5.1
Using 0.5.0 would only cause an issue if someone had it installed / cached locally from before it was re-tagged to its current sha, which shouldn't be an issue in our CI.

**Comment by a-roberts** [comment]
Cool, I'll close this off one then (and if there ever is a need to get it bumped that's a new PR for a new reason!), thanks
