### ISSUE TITLE
Find a home for `taps` formulas

### ISSUE THREAD

**Issue by chmouel** [tektoncd/plumbing#43]
For the [CLI](https://github.com/tektoncd/cli) we want to have a homebrew `tap` repository to install easily on OSX. 

We have currently one on my own github user at :

https://github.com/chmouel/homebrew-tektoncd-cli/

which is generated at release time with goreleaser : 

https://github.com/tektoncd/cli/blob/master/.goreleaser.yml#L48-L64

It would be better we have this to something more official, the solutions i can see are  : 

1) Move to the official core Formulas on https://github.com/Homebrew/homebrew-core/

Pros: 
- it's official yeah! 
- It's easier for our user (no tap to tap)

Cons:
- We are dependent of being approved before release announcement etc..
- We can't use goreleaser (not kosher enough for core formula), it's a manual update and no one (or at least me :)) like the extra release steps.

2) Have a tektoncd/homebrew-tools

Pros: 

Related: https://github.com/tektoncd/cli/issues/99

 - User just have to do `brew tap tektoncd/tools` and this will subscribe to the tektoncd repo. 
We can then have multiple formulas in there for different tools that we need.

Cons:

 - I can't see much to be honest, but opinions may diverge

Another suggestion has been made to have it directly in the tektoncd/cli repo, but brew require an adjacent repo with a homebrew prefix. :( 

My vote would be to create a new github repo and use it as tap and not having in the official  core repo. 

/cc @siamaksade  @vdemeester @sthaha  

/kind question

**Comment by siamaksade** [comment]
Third options is to move it to https://github.com/Homebrew/homebrew-cask

**Comment by chmouel** [comment]
@siamaksade i don't believe that would be a great fit, I think `cask`'s are for binary OSX gui applications, i.e: 

![image](https://user-images.githubusercontent.com/98980/60272095-d0db0400-98f3-11e9-945d-4f28c2208309.png)

**Comment by siamaksade** [comment]
Minikube and minishift are also in Homebrew Cask

**Comment by chmouel** [comment]
that's interesting thanks @siamaksade (altho i don't understand that decision to allow everything in `homebrew/cask` but that's probably a question for another repo), if we move to that repo we will loose `goreleaser` homebrew auto release and have to update manually, wdyt @vdemeester ?

**Comment by StevenACoffman** [comment]
Could you use goreleaser with tektoncd/homebrew-tools and then 
on a commit there webhook would automate using a personal access token to make a pull request  to https://github.com/Homebrew/homebrew-core/
If only those manual steps could be hooked into some sort of _pipeline_😀

**Comment by chmouel** [comment]
I don't believe the formula generated by `goreleaser` is good enough for homebrew-core or at least according to the documentation : 

https://goreleaser.com/homebrew/

![image](https://user-images.githubusercontent.com/98980/60829786-087c6280-a1b6-11e9-8cf9-678698255938.png)

**Comment by StevenACoffman** [comment]
Yeah, whatever is required for homebrew-core formulas (must build from source?), it's still driven off of a git sha and a release version tag, and at the time of a release, no other changes to the file really need to be done.

For instance: [homebrew-core formula for goreleaser](https://github.com/Homebrew/homebrew-core/blob/master/Formula/goreleaser.rb)

To update a homebrew-core formula for a new release, if you have the release git commit and tag you can automate making a pull request to homebrew-core to change the file if you have a github personal access token.

**Comment by chmouel** [comment]
I have tried to submit it to homebrew-core : 

https://github.com/Homebrew/homebrew-core/pull/43360

but I haven't seen that much action since 20 days ago, 

I would be worry that every update would take quite some time,

I think it would be best if we have a homebrew-tektoncd in the tektoncd github organisation so we can control it .

wdyt @bobcatfish @vdemeester @StevenACoffman @siamaksade 

(and taps are an official channel for brew)

**Comment by siamaksade** [comment]
+1

**Comment by chmouel** [comment]
/close 

https://github.com/tektoncd/homebrew-tools is live
