### ISSUE TITLE
Setup triage party

### ISSUE THREAD

**Issue by afrittoli** [tektoncd/plumbing#435]
Setup triage party (https://github.com/google/triage-party#triage-party-) in the tekton infra so that we can play with it for a bit and decide whether it helps Tekton and we want to adopt it or not.

**Comment by bobcatfish** [comment]
Thanks @tstromberg!!

**Comment by tstromberg** [comment]
Please let me know if you need any help getting it setup right -- as well as any ideas you have on how to improve Triage Party.

**Comment by vdemeester** [comment]
I really like that idea :heart_eyes_cat:

**Comment by afrittoli** [comment]
There are example manifests for k8s available: https://github.com/google/triage-party/blob/master/deploy/kubernetes/configmap.yaml

I would suggest we do the same that we did with prow, copy the manifests into the plumbing repo a deploy the config from git continuously.

**Comment by afrittoli** [comment]
> Please let me know if you need any help getting it setup right -- as well as any ideas you have on how to improve Triage Party.

Thanks @tstromberg, I do have a question. AFAIU, triage party will impersonate a functional user in github. Since the app will be exposed publicly, I would like to create a dedicated triage-party user and give it minimal access rights, to avoid giving the world more power than they should have.  What does the setup used by other projects look like?

**Comment by tstromberg** [comment]
@Andree - I just happened to clarify the permissions issue yesterday:
https://github.com/google/triage-party#requirements

Triage Party is an explicitly read-only interface by design, so the only
required API permission is `public_repo` (read-only).

Kubernetes created a new-user for Triage Party, which I would recommend as
a best practice. I'm using my personal for other projects, but in
the interest of paranoia, less permissions is always the best. If you
happen to have a read-only bot for other tools, it's probably safe to
re-use.

**Comment by wlynch** [comment]
Didn't know about this issue, but I inadvertently discovered this after talking with one of my friend's involved in a k8s SIG and set up a demo instance here: https://triage-party-u2qx2zgfja-uc.a.run.app/

Currently runs in one of my test projects, but this was pretty easy to set up so we should be able to recreate it pretty easily in a Tekton owned project.

> Since the app will be exposed publicly, I would like to create a dedicated triage-party user and give it minimal access rights, to avoid giving the world more power than they should have.

+1. You can generate a personal access token with only public read permissions, but the other thing to be concerned about is [quota](https://developer.github.com/v3/rate_limit/) (which I assume is the primary reason why Triage Party requires a token). We should probably use https://github.com/tekton-robot so we don't exhaust someone's personal quota.
