### ISSUE TITLE
Delete old TaskRuns/PipelineRuns in dogfoding?

### ISSUE THREAD

**Issue by dibyom** [tektoncd/plumbing#439]
# Expected Behavior

The cluster should only contain the last N runs. 

# Actual Behavior

We have runs created 270 days ago. This makes both `tkn` and `kubectl` (as well as the dashboard) very slow to use.

```
 k get prs --sort-by=.metadata.creationTimestamp|wc -l
674

k get trs --sort-by=.metadata.creationTimestamp|wc -l
7687

```

# Additional Info

**Comment by bobcatfish** [comment]
Yikes, good point!

I wonder if a cron is our best bet here?

**Comment by dibyom** [comment]
Yeah a CronJob is I think what we suggested in Pipelines.

**Comment by vdemeester** [comment]
We can start with a cronjob using `tkn … delete` maybe (with the `--keep` flag) and maybe, experiment with a garbage collector (that would allow us do smarter things, like keeping some based on labels or annotations, …)

**Comment by afrittoli** [comment]
I started working on this.
