### ISSUE TITLE
[Question] Does PROW and Tekton will work together for CICD in long term

### ISSUE THREAD

**Issue by gyliu513** [tektoncd/plumbing#530]
I found there are already some documents like https://github.com/tektoncd/plumbing/blob/master/docs/prow.md etc can help people to set up PROW + Tekton do the CI work, here my question is: What is the long term plan for PROW and Tekton? As far as I can see, most of the Kubernetes eco-ssystem projects are still using PROW, so not sure what is the future plan for PROW and Tekton, would love to see some comments for this. Thanks!

**Comment by bobcatfish** [comment]
Hey @gyliu513 ! Folks from Prow could probably give the best answer here, e.g. @cjwagner @coryrc

**Comment by coryrc** [comment]
From Prow's standpoint, we want to provide Tekton first-class support, including integrating it into the existing UI and/or support the Tekton dashboard (which I just discovered). Triggers will probably be the last thing supported.

I'm trying to spearhead Tekton w/ Prow in a few smaller projects. If I'm successful it might come to kubernetes!

**Comment by coryrc** [comment]
Help is welcome though! :-D

**Comment by gyliu513** [comment]
One more question here: What is the value of Tekton bring to PROW? 

@sethpeterson

**Comment by coryrc** [comment]
How do you choose to glue together the components of your pipeline? Bash like Knative? kubetest+bazel+bash like Kubernetes? Both those stacks are getting a lot of redevelopment because they aren't adapting to new needs. Tekton should.

**Comment by gyliu513** [comment]
@coryrc thanks, would you show more detail, like some examples fro the `new needs`? This will be very helpful ;-)

**Comment by gyliu513** [comment]
thanks all for the info here, this really helps!
