### ISSUE TITLE
Update prow document to clarify it support latest tekton pipeline

### ISSUE THREAD

**Issue by gyliu513** [tektoncd/plumbing#546]
Based on comments here https://github.com/kubernetes/test-infra/issues/13948#issuecomment-549046368 and https://github.com/kubernetes/test-infra/pull/15072 , prow can work with tekton 0.8.0 now.

Seems the document here https://github.com/tektoncd/plumbing/blob/master/docs/prow.md#tekton-pipelines-with-prow also need some update.

![image](https://user-images.githubusercontent.com/4461983/91271228-6ef28480-e7ac-11ea-879d-b412b090adec.png)

FYI @eddycharly

**Comment by eddycharly** [comment]
Yep, it supports v1alpha1 only though.

**Comment by gyliu513** [comment]
Thanks @eddycharly , but I think we can update the document claim that pipeline version can be 0.8.0?

**Comment by eddycharly** [comment]
Sure, I just wanted to point out the limitation.

**Comment by gyliu513** [comment]
@eddycharly can I say the prow only support pipeline 0.8.0, or also the 0.8.0-, like 0.7, 0.6 etc?

**Comment by eddycharly** [comment]
From the prow go mod `github.com/tektoncd/pipeline v0.13.1-0.20200625065359-44f22a067b75`, i think it supports pipelines up to v0.13.1.

In https://github.com/kubernetes/test-infra/blob/69851ff05ca3bcd81af04543bd368d4502051917/prow/apis/prowjobs/v1/types.go#L161 : `PipelineRunSpec *pipelinev1alpha1.PipelineRunSpec`.

So i think that saying prow supports pipelines v1alpha1 up to v0.13.1 should be pretty close.

**Comment by vdemeester** [comment]
@gyliu513 thx for the issue. I do agree with @eddycharly, "saying prow supports pipelines v1alpha1 up to v0.13.1 should be pretty close.".

**Comment by gyliu513** [comment]
thanks @eddycharly @vdemeester , let me create a PR soon for this.
