### ISSUE TITLE
tekton-releases bucket organization

### ISSUE THREAD

**Issue by vdemeester** [tektoncd/plumbing#57]
Currently, we are using `tekton-releases` bucket to store releases yamls for `tektoncd/pipeline`. We may want to use it for other tektoncd projects, like `dashboard` (that also has a yaml or two for releases). My question is:

- Should we create another bucket for those, like `dashboard-releases` ?
- Should we have some sort of folder layout for the future ?

```
pipeline/
  latest/
  previous/
dashboard/
  latest/
  previous/
```

/cc @bobcatfish

**Comment by afrittoli** [comment]
I would go for one bucket / multiple folders.
We should move pipeline artifacts into their own dedicated folder, and hopefully eventually we can move the release tasks / pipelines to the plumbing repo for all projects to use.
