### ISSUE TITLE
needs-rebase plugin not working

### ISSUE THREAD

**Issue by bobcatfish** [tektoncd/plumbing#583]
# Expected Behavior

Prow components are able to use "external plugin" (https://github.com/kubernetes/test-infra/tree/master/prow/plugins#external-plugins) needs-rebase

# Actual Behavior

@afrittoli noticed that components such as hook and plank are full of this error:

```
"Post http://needs-rebase: dial tcp: lookup needs-rebase on 10.55.240.10:53: no such host" 
```

It's not clear if this is causing a problem or not (might be related to #582)

**Comment by vdemeester** [comment]
https://github.com/tektoncd/plumbing/pull/585 should fix that

**Comment by vdemeester** [comment]
```
default/hook-774978fc77-g5xsr[hook]: {"component":"hook","event-GUID":"a587c600-fcaa-11ea-85e0-49013a2a50a6","event-type":"issue_comment","external-plugin":"needs-rebase","file":"prow/hook/server.go:202","func":"k8s.io/test-infra/prow/hook.(*Server).demuxExternal.func1","level":"info","msg":"Dispatched event to external plugin","time":"2020-09-22T08:07:25Z"}
```

Seems like it is working.
/close
