### ISSUE TITLE
Handle new experimental task-loops folder

### ISSUE THREAD

**Issue by GregDritschler** [tektoncd/plumbing#604]
# Expected Behavior

Plumbing handles pull requests for the new experimental task-loops folder.

# Actual Behavior

tbd

# Steps to Reproduce the Problem

1.
2.
3.

# Additional Info

**Comment by GregDritschler** [comment]
@afrittoli Here is the issue you requested to be opened for the new experimental task loops folder.

**Comment by vdemeester** [comment]
@afrittoli what is the status here ?
