### ISSUE TITLE
Tag gcr.io/tekton-releases/dogfooding/tkn with tkn Release Versions

### ISSUE THREAD

**Issue by danielhelfand** [tektoncd/plumbing#608]
# Expected Behavior

The `gcr.io/tekton-releases/dogfooding/tkn` image should have tags for each released version of `tkn`. 

# Actual Behavior

The image only supports the latest version.

# Steps to Reproduce the Problem

1. Run `docker run -it gcr.io/tekton-releases/dogfooding/tkn:v0.12.0`
2. See error for unavailable image/tag

# Additional Info

This would allow users to more easily use specific versions of `tkn` in steps. An example of this is the [`tkn` catalog Task](https://github.com/tektoncd/catalog/blob/972bca5c5642a056c28ff1976c30c7367e6a9c3a/task/tkn/0.1/tkn.yaml#L18), which can only use the latest version of `tkn`. 

/kind feature

**Comment by ibexmonj** [comment]
would be interesting in using images with tags as well. Any update on this issue ?

**Comment by vdemeester** [comment]
/remove-lifecycle stale
I think there is another issue around this (official image for `tkn`) in `tektoncd/cli`, but in any case, this is still something we should aim for.
