### ISSUE TITLE
Nightly releases not pulling in latest yaml configs from repo

### ISSUE THREAD

**Issue by wlynch** [tektoncd/plumbing#624]
# Expected Behavior

Commits to project tekton folders that modify resources get applied before nightly pipelines run.

# Actual Behavior

Nightly pipeline uses old tekton/publish.yaml resource (https://gist.github.com/wlynch/c673aad7cf038d559ab62ae65bc04068), which breaks the nightly build. In this case,

```
    - name: builtBaseImage
      type: image
```

is included in the image, causing the validation to fail.

[PipelineRun](https://dashboard.dogfooding.tekton.dev/#/namespaces/default/pipelineruns/pipeline-release-nightly-j67h4) status:

```
status:
  completionTime: "2020-10-27T02:00:18Z"
  conditions:
  - lastTransitionTime: "2020-10-27T02:00:18Z"
    message: 'invalid output resources for task publish-tekton-pipelines: Task''s
      declared required resources are missing from the TaskRun: [builtBaseImage]'
    reason: PipelineValidationFailed
    status: "False"
    type: Succeeded
```

# Steps to Reproduce the Problem

https://github.com/tektoncd/pipeline/commit/adc4cfa733af86874017d07459cc5ad62bf82bd3#diff-ebf66cb40b85597c895c09c9e8916529820e1dceec0973c077096ed554c1443a is the offending commit that introduced the change.

# Additional Info

https://github.com/tektoncd/pipeline/commit/adc4cfa733af86874017d07459cc5ad62bf82bd3 was submitted 2020-10-26T14:24Z, while the publish-tekton-pipelines task was created 2020-10-26T15:07:08Z, which likely means it is trying to apply the Task, but it's using the wrong version.

I couldn't find instructions for how the dogfooding cluster is updating these resources - I'm not confident that manually applying the correct yaml will fix this, and won't just be overwritten in the next daily run. We should look into increasing documentation here as another AI.

/cc @afrittoli

**Comment by vdemeester** [comment]
That's my fault, I had to re-vert the task on the cluster to do the `v0.17.2` release and did not re-apply it right after.
This should be fixed now.

**Comment by afrittoli** [comment]
This has been fixed by https://github.com/tektoncd/plumbing/pull/714.
Now tekton resources for pipeline, triggers and dashboard are installed nightly.
