### ISSUE TITLE
Support e2e testing with kind

### ISSUE THREAD

**Issue by imjasonh** [tektoncd/plumbing#631]
### Feature request

Currently e2e tests [create a regional GKE cluster using kubetest](https://github.com/tektoncd/plumbing/blob/b086b5c7ad03e01520aa166b3f1a97fd643ceb54/scripts/e2e-tests.sh#L251-L256) -- this takes a few minutes to set up, and can cost money if resources leak. Requiring a GCP account and billing might present a barrier to some contributors. We also lose some control over the version of Kubernetes installed on the GKE cluster, since GKE doesn't support every old version of Kubernetes, or immediately support new versions as they're released. We're also limited by GKE's chosen cluster configuration and feature flags.

We should support an e2e testing mode using [`kind`](https://kind.sigs.k8s.io/), which simulates a K8s cluster using local Docker containers. `kind cluster create` typically finishes in a few seconds, and [lets you configure a K8s version](https://kind.sigs.k8s.io/docs/user/quick-start/#setting-kubernetes-version), [configure feature flags](https://kind.sigs.k8s.io/docs/user/quick-start/#enable-feature-gates-in-your-cluster), and more.

Though they look like multi-node clusters, all resources are consumed from the machine running the cluster, so this might limit the size of the cluster we can create, especially for local testing. We shouldn't remove the GKE option, and should continue to run all CI tests against GKE, in addition to kind.

### Use case

Since clusters are easier to create and destroy, we could write tests against a small kind cluster to test resource-exhaustion scenarios, tests that target specific K8s versions or feature flag configurations, install mutating webhooks to inject sidecars, etc.

### Prior Art

Knative runs tests in kind, see https://github.com/knative/hack/blob/master/test/e2e-kind.sh and Prow changes [here](https://github.com/knative/test-infra/pull/2427).

@mattmoor has done a lot of kind testing for mink, and might be able to provide guidance if we get stuck.

@afrittoli has contributed [a script in this repo](https://github.com/tektoncd/plumbing/blob/master/hack/tekton_in_kind.sh) to create a kind cluster with Tekton installed.

**Comment by mattmoor** [comment]
I am in fact running the Tekton tests in KinD.  Last night I pulled the setup into a script, which I'll probably move into `knative.dev/hack`: https://github.com/mattmoor/mink/blob/master/hack/setup-kind.sh

I highlight this because I want to centralize our KinD setup so that we can codify all kinds of best practices and cluster oddities (like randomizing `.svc.cluster.local`, or eventually dual stack).  Things that may be hard or impossible to (maybe ever) test on GKE.

**Comment by mattmoor** [comment]
I realized that some of the things I added last night (like metallb, kudos to @benmoss) might be useful for tektoncd/triggers.

**Comment by yaoxiaoqi** [comment]
Hi Andrea @afrittoli , are you working on this currently? I would like to know if there's anything I can do to help.

**Comment by mattmoor** [comment]
cc @chizhg did some work to support this on Prow
