### ISSUE TITLE
Linting should catch exported values without docstrings

### ISSUE THREAD

**Issue by bobcatfish** [tektoncd/plumbing#64]
# Expected Behavior

If someone opens a PR with exported values that don't have docstrings, linting should prompt them to add a docstring.

# Actual Behavior

Nothing happens! e.g. in https://github.com/tektoncd/triggers/pull/63

# Steps to Reproduce the Problem

1. Add a new type to a `_types.go` in the triggers repo or pipeline repo, e.g.

```
type SomeNewThing struct {
	TriggerBinding     TriggerBindingRef  `json:"triggerBinding"`
	TriggerTemplate    TriggerTemplateRef `json:"triggerTemplate"`
	ServiceAccountName string             `json:"serviceAccountName"`
}
```
2. Open a PR
3. Note that the linting doesnt say anything! But actually if you opened this in an editor (e.g. vscode with the Go plugin) you'd get a warning that there should be docstrings for SomeNewThing and its attributes

# Additional Info

From @vtereso :

```
Adding `-E golint` to our lint command (`golangci-lint run`) _should_ allow us to get [this behavior](https://github.com/golang/lint/blob/master/lint.go), but when I tried it only complained about naming stutter errors. 
```

(Those stutter errors are probably decent to surface as well imo! Why not :D )

**Comment by vdemeester** [comment]
@bobcatfish yeah, we should add this to the linter in the golangci configuration file. Right now, each repository has its own (see `tektoncd/cli` or `tektoncd/triggers`), we could have a default one, shared by all maybe ?

**Comment by bobcatfish** [comment]
Feels like something we should do, if we haven't already?
/remove-lifecycle stale.

**Comment by bobcatfish** [comment]
dang it

/remove-lifecycle stale

**Comment by bobcatfish** [comment]
SHOOT
