### ISSUE TITLE
CI is failing on yamllint

### ISSUE THREAD

**Issue by chmouel** [tektoncd/plumbing#698]
# Expected Behavior

# Actual Behavior

CI is bailing out with an error that looks like this : 

```
+ yamllint bots/buildcaptain/config bots/mariobot/config pipelinerun-logs/config boskos gubernator prow robocat tekton
[Errno 2] No such file or directory: 'bots/buildcaptain/config'
```

Full log of the PR

https://dashboard.dogfooding.tekton.dev/#/namespaces/tektonci/pipelineruns/tekton-yamllint-l88rx?pipelineTask=lint&step=lint

# Steps to Reproduce the Problem

Send a PR and see the log of the failure

/kind bug

**Comment by afrittoli** [comment]
This is caused by a change in the name of the `buildbot` folder - could you rebase your PR 🙏  It will work then.
