### ISSUE TITLE
Catlin: Catlin does not validates all the resources passed as an argument in the command

### ISSUE THREAD

**Issue by PuneetPunamiya** [tektoncd/plumbing#715]
# Expected Behavior

Catlin should validate all the resources passed as an argument in the command

# Actual Behavior

Currently Catlin validates only the first resource in the argument and ignores the remaining resources and not validates them 

For e.g.
```
./catlin validate tmp/catalog/task/buildkit/0.1/buildkit.yaml tmp/catalog/task/build-push-gke-deploy/0.1/build-push-gke-deploy.yaml

HINT : Task: tekton.dev/v1beta1 - name: "buildkit" is missing a readable display name annotation("tekton.dev/displayName")
WARN : Step "build-and-push" uses image "$(params.BUILDKIT_CLIENT_IMAGE)" that contains variables; skipping validation
```

In the above example as we can see Catlin does not validates the second resource

**Comment by vinamra28** [comment]
I guess it's a feature and not a bug :sweat_smile: 
/kind feature
