### ISSUE TITLE
Catlin: Catlin does not validates the resource even if the folder is passed in the command

### ISSUE THREAD

**Issue by PuneetPunamiya** [tektoncd/plumbing#716]
# Expected Behavior

Catlin should validate the resource even if the folder is passed in the command

# Actual Behavior

Currently Catlin only supports file validation for a resource and not the folder structure 

For e.g.

```
./catlin validate tmp/catalog/task/buildkit/0.1/

Error: no such file - tmp/catalog/task/buildkit/0.1
```

In the above example Catlin gives an error and not finds the resource file and hence does not validates the resource.
Hence Catlin should validate the resource even if folder is passed in the command

**Comment by vinamra28** [comment]
/unassign @PuneetPunamiya
/assign
Same I guess it's a feature :sweat_smile: 
/kind feature
