### ISSUE TITLE
Transfer GCP projects ownership entirely to CDF and Tekton

### ISSUE THREAD

**Issue by bobcatfish** [tektoncd/plumbing#865]
### Feature request

When we first setup test infrastructure for Tekton, Google employees created [GCP projects](https://github.com/tektoncd/plumbing/blob/main/docs/README.md#gcp-projects) (projects for the test infrastructure, projects to run test clusters on and projects for storing container images, etc.). However, the way these were created meant that they are subject to Google specific restrictions, the most prominent of which is that only Google employees can have complete admin control over the clusters.

At this point, the CDF is paying the bills for theses clusters, so there is no reason why only Google employees should have access.

This issue is tracking the need to create new clusters, entirely owned by the CDF and Tekton, so that the Tekton team can be free to decide who has access to what.

The trickiest part of pulling this off will probably be dealing with the released images and configuration, e.g. https://storage.googleapis.com/tekton-releases/pipeline/latest/release.yaml which contains in its URL the name of one of these projects and refers to published images such as gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/webhook:v0.26.0@sha256:79cf8b670ab008d605362641443648d9ac0ff247f1f943bb4d5209716a9b49fa which also refer to buckets within one of these projects; we'll need to find a way to seamlessly redirect these to the new projects.

### Use case

* Allowing completely admin access to all GCP projects by all governing board members, not just Google employees
* When new folks start working on Tekton and want to work on Build Captain rotation or similar, not having to find a Google employee to give them access

**Comment by lbernick** [comment]
As discussed in today's productivity WG, we may want to tackle #920 along with this issue.

**Comment by bobcatfish** [comment]
A couple of quick updates here:

* @dibyom and @wlynch have recently found out that we may be able to simply move the existing projects such that they won't be considered google internal anymore (vs having to recreate them and migrate)
* I put together [an initial todo list](https://docs.google.com/document/d/1h-Q9NXJxv9b6qAJM4OTKDpDMwXZz8c-quCLsYvRyIu0/edit#) with everything we'd want to do to clean these projects up - it goes slightly beyond the scope of this particular issue (should be editable by [tekton-dev](https://github.com/tektoncd/community/blob/main/contact.md#mailing-list))

**Comment by dibyom** [comment]
cc https://github.com/cdfoundation/foundation/issues/359

**Comment by dibyom** [comment]
This is now complete!
All Tekton projects are now under the LinuxFoundation organization under a Tekton Project Folder. The billing account has also been updated to a CDF billing account!
