### ISSUE TITLE
Migrate Tekton based CI to Workspaces

### ISSUE THREAD

**Issue by sbwsg** [tektoncd/plumbing#885]
### Feature request

We have a [ci-workspace](https://github.com/tektoncd/plumbing/tree/main/tekton/ci-workspace) folder for to migrate jobs from the [ci](https://github.com/tektoncd/plumbing/tree/main/tekton/ci) folder. As part of this process we should remove use of Conditions and PipelineResources, moving instead to When Expressions and Workspaces.

Here's [a good example of migrating yamllint](https://github.com/tektoncd/plumbing/pull/875) to the newer features.

**Comment by bobcatfish** [comment]
In that example PR where I migrated yamllint, I made the change in the old folder and didnt realize that the intention was that updated jobs would be moved into https://github.com/tektoncd/plumbing/tree/main/tekton/ci-workspace so that's still TODO

**Comment by afrittoli** [comment]
Fixed by these PRs:

- Label check https://github.com/tektoncd/plumbing/pull/948
- Golangci lint https://github.com/tektoncd/plumbing/pull/951
- yamllint and final cleanup https://github.com/tektoncd/plumbing/pull/953
