### ISSUE TITLE
Use `Environment Variables` instead of `Parameters` in `Script`

### ISSUE THREAD

**Issue by jerop** [tektoncd/plumbing#971]
Today, several `Tasks` use `Parameters` in `Script` that Tekton Pipelines interpolate - for example:
https://github.com/tektoncd/plumbing/blob/df1c25d54ffae0ba72d1e097e17b0fab5f03d209/tekton/ci/jobs/tekton-kind-label.yaml#L30-L37

This presents a few challenges:
- it is fragile e.g. a quote in the `Parameter` would make the `Script` invalid and the `Task` would fail 
- an interpolated `Script` is a security risk because it can be used to extract information  

We need to migrate to using `Environment Variables` which are not interpolated in `Script`.

We also need to warn users when they use `Parameters` in `Scripts`. 

#### References
- [Don't use interpolation in scripts or string arguments](https://github.com/tektoncd/catalog/blob/main/recommendations.md#dont-use-interpolation-in-scripts-or-string-arguments)
- https://github.com/tektoncd/catalog/pull/711
- https://github.com/tektoncd/plumbing/pull/911#discussion_r773176609

#### Implementation

- [ ] https://github.com/tektoncd/plumbing/pull/973
- [ ] https://github.com/tektoncd/plumbing/pull/974
- [ ] https://github.com/tektoncd/plumbing/pull/975
- [ ] https://github.com/tektoncd/plumbing/pull/976
- [ ] https://github.com/tektoncd/plumbing/pull/977
- [ ] https://github.com/tektoncd/plumbing/pull/978

**Comment by jerop** [comment]
@sbwsg there are several of them to be fixed, so we can collaborate on this - had already written a fix for publish release task that I just pushed in https://github.com/tektoncd/plumbing/pull/973

/assign

**Comment by jerop** [comment]
- [ ] ./tekton/ci/interceptors/add-pr-body/tekton/publish.yaml:
- [ ] ./tekton/ci/interceptors/add-pr-body/tekton/release-pipeline.yaml:
- [ ] ./tekton/ci/interceptors/add-team-members/tekton/publish.yaml:
- [ ] ./tekton/ci/interceptors/add-team-members/tekton/release-pipeline.yaml:
- [ ] ./tekton/ci/jobs/tekton-catalog-catlin-lint.yaml:
- [ ] ./tekton/ci/jobs/tekton-image-build.yaml:
- [ ] ./tekton/ci/jobs/tekton-kind-label.yaml:
- [ ] ./tekton/ci/shared/common-tasks.yaml:
- [ ] ./tekton/mario-bot/mario-github-comment.yaml:
- [ ] ./tekton/resources/cd/catalog-template.yaml:
- [ ] ./tekton/resources/cd/cleanup-template.yaml:
- [ ] ./tekton/resources/cd/configmap-template.yaml:
- [ ] ./tekton/resources/cd/folder-template.yaml:
- [ ] ./tekton/resources/cd/helm-template.yaml:
- [ ] ./tekton/resources/images/docker-multi-arch-template.yaml:
- [ ] ./tekton/resources/images/ko-multi-arch-template.yaml:
- [ ] ./tekton/resources/nightly-release/tasks.yaml:
- [ ] ./tekton/resources/nightly-tests/base/deploy_tekton_component.yaml:
- [ ] ./tekton/resources/nightly-tests/bastion-p/k8s_cluster_setup.yaml:
- [ ] ./tekton/resources/nightly-tests/bastion-z/k8s_cluster_setup.yaml:
- [ ] ./tekton/resources/release/base/github_release.yaml:
- [ ] ./tekton/resources/release/base/install_tekton_release.yaml:
- [ ] ./tekton/resources/release/base/prerelease_checks.yaml:

**Comment by sbwsg** [comment]
* [x]  ./tekton/ci/interceptors/add-pr-body/tekton/publish.yaml:
* [ ]  ./tekton/ci/interceptors/add-pr-body/tekton/release-pipeline.yaml:
* [ ]  ./tekton/ci/interceptors/add-team-members/tekton/publish.yaml:
* [ ]  ./tekton/ci/interceptors/add-team-members/tekton/release-pipeline.yaml:
* [ ]  ./tekton/ci/jobs/tekton-catalog-catlin-lint.yaml:
* [ ]  ./tekton/ci/jobs/tekton-image-build.yaml:
* [ ]  ./tekton/ci/jobs/tekton-kind-label.yaml:
* [ ]  ./tekton/ci/shared/common-tasks.yaml:
* [ ]  ./tekton/mario-bot/mario-github-comment.yaml:
* [ ]  ./tekton/resources/cd/catalog-template.yaml:
* [ ]  ./tekton/resources/cd/cleanup-template.yaml:
* [ ]  ./tekton/resources/cd/configmap-template.yaml:
* [ ]  ./tekton/resources/cd/folder-template.yaml:
* [ ]  ./tekton/resources/cd/helm-template.yaml:
* [ ]  ./tekton/resources/images/docker-multi-arch-template.yaml:
* [ ]  ./tekton/resources/images/ko-multi-arch-template.yaml:
* [ ]  ./tekton/resources/nightly-release/tasks.yaml:
* [ ]  ./tekton/resources/nightly-tests/base/deploy_tekton_component.yaml:
* [ ]  ./tekton/resources/nightly-tests/bastion-p/k8s_cluster_setup.yaml:
* [ ]  ./tekton/resources/nightly-tests/bastion-z/k8s_cluster_setup.yaml:
* [ ]  ./tekton/resources/release/base/github_release.yaml:
* [ ]  ./tekton/resources/release/base/install_tekton_release.yaml:
* [ ]  ./tekton/resources/release/base/prerelease_checks.yaml:
