### ISSUE TITLE
Pinned / checksum verified dependencies

### ISSUE THREAD

**Issue by wlynch** [tektoncd/plumbing#996]
### Feature request

I noticed that in many of our Dockerfiles ([example](https://github.com/tektoncd/plumbing/blob/main/tekton/images/ko-gcloud/Dockerfile)), we use tags instead of SHAs for referencing docker images, .tgzs, Go modules, etc. Although this is not a hard requirement for SLSA L4, it'd be great if we could start pinning our dependencies (or where we can't pin, verify via checksum) as much as possible.

### Use case

Good for general supply chain security, requirement for SLSA L4.

**Comment by afrittoli** [comment]
Thanks @wlynch - it sounds like a good idea. 
Would you like to break this down in a series of small tasks so we can start implementing them / tag then as help wanted?

There are other places we'll need to do this as well, I started doing some pinning in the pipeline and triggers release pipeline: https://github.com/tektoncd/pipeline/pull/4639
